# copy secret from global-hub rhacm-policies namespace to managed-hub rhacm-policies namespace
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bgp-password
  namespace: rhacm-policies
data:
  '{{hub copySecretData "rhacm-policies" "bgp-password" hub}}'
---
