---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: test-app
    patch: |
      - op: replace
        path: /spec/template/spec/source/path
        value: kustomize-deployments/test-app/overlays/prod
      - op: replace
        path: /spec/template/spec/destination/namespace
        value: test-prod
      - op: replace
        path: /spec/template/spec/info/0/value
        value: prod
...
