= ArgoCD Commands
== Login to Hub OpenShift GitOps

[source,bash]
----
argocd login "$(oc -n openshift-gitops get route openshift-gitops-server -o jsonpath={'.spec.host}'):443" \
  --skip-test-tls --username admin \
  --password "$(oc -n openshift-gitops get secret openshift-gitops-cluster -o jsonpath='{.data.admin\.password}' | base64 -d)"
----

== Add Clusters to ArgoCD

[NOTE]
====
This is not required when RHACM integration with OpenShift GitOps is enabled. RHACM automatically adds ManageClusters to OpenShift GitOps. and syncs all labels on the ManageClusters to ArgoCD clusters.
====

[source,bash]
----
argocd cluster add cluster01 --server="$(oc -n openshift-gitops get route openshift-gitops-server -o jsonpath='{.spec.host}')" --label rhacs-secured-cluster=enable --insecure --yes
----

The command performs the followings:

- on the target/managed cluster:
** creates `argocd-manager` ServiceAccount in `kube-system` namespace.
** grants `argocd-manager` ServiceAccount cluster-admin privileges (ClusterRole: `argocd-manager-role`, ClusterRoleBinding: `argocd-manager-role-binding`).
** creates a bearer token (that never expire, no `exp` claim) with the `argocd-manager` ServiceAccount.
- on the hub cluster:
** create a secret with the properties:
*** name: cluster01
*** server: url of the target/managed
*** config: dict containing bearer token (`bearerToken`)
