---
object-templates-raw: |
  {{hub $label_selector := "sync-secret/type=global-hub,sync-secret/env=prod" hub}}
  {{hub range $secret := (lookup "v1" "Secret" "rhacm-policies" "" $label_selector).items hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: {{hub index $secret.metadata.annotations "sync-secret/target-name" hub}}
        namespace: rhacm-policies
        labels:
          {{hub range $key, $value := merge (dict "sync-secret/type" "managed-hub") $secret.metadata.labels hub}}
          {{hub $key hub}}: "{{hub $value hub}}"
          {{hub end hub}}
        annotations:
          {{hub range $key, $value := $secret.metadata.annotations hub}}
          {{hub $key hub}}: "{{hub $value hub}}"
          {{hub end hub}}
      data:
        {{hub range $key, $value := $secret.data hub}}
        {{hub $key hub}}: "{{hub $value hub}}"
        {{hub end hub}}
    {{hub if eq (index $secret.metadata.annotations "sync-secret/aux") "sync" hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: {{hub index $secret.metadata.annotations "sync-secret/target-name" hub}}
        namespace: {{hub index $secret.metadata.annotations "sync-secret/target-namespace" hub}}
        labels:
          {{hub range $key, $value := $secret.metadata.labels hub}}
            {{hub if ne (printf "%.12s" $key) "sync-secret/" hub}}
          {{hub $key hub}}: "{{hub $value hub}}"
            {{hub end hub}}
          {{hub end hub}}
        annotations:
          {{hub range $key, $value := $secret.metadata.annotations hub}}
            {{hub if ne (printf "%.12s" $key) "sync-secret/" hub}}
          {{hub $key hub}}: "{{hub $value hub}}"
            {{hub end hub}}
          {{hub end hub}}
      data:
        {{hub range $key, $value := $secret.data hub}}
        {{hub $key hub}}: "{{hub $value hub}}"
        {{hub end hub}}
    {{hub end hub}}
  {{hub end hub}}
...
