---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: rhacs-central
    patch: |
      - op: add
        path: /spec/sources/0/helm/valuesObject
        value:
            centralDB:
              resources:
                limits:
                  cpu: "4"
                  memory: 8Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
            central:
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "1"
                  memory: 2Gi
            minimumAccessRole: Admin
...
