---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-managed-hub-app-of-apps           # prefix Application name with 00 for sorting purpose
  namespace: openshift-gitops
  labels:
    applications: managed-hub-app-of-apps
  annotations:
    argocd.argoproj.io/sync-wave: "1000"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: iac-gitops
  source:
    repoURL: https://github.com/bkkhoo/argocd.git
    path: root-app/managed-hub/dev
    targetRevision: main
  destination:
    name: in-cluster
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: false       # the config here modify pre-existing resources that are part of openshift
      selfHeal: true     # do not delete the resources when they are no longer defined in git
    syncOptions:
      - CreateNamespace=true
...
