---
evictionSoft:
  memory.available: "2Gi"
  nodefs.available: "15%"
  nodefs.inodesFree: "10%"
  imagefs.available: "15%"
  imagefs.inodesFree: "10%"
  pid.available: "10%"
evictionHard:
  memory.available: "1Gi"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
  imagefs.available: "10%"
  imagefs.inodesFree: "5%"
  pid.available: "5%"
evictionSoftGracePeriod:
  memory.available: "3m"
  nodefs.available: "3m"
  nodefs.inodesFree: "3m"
  imagefs.available: "3m"
  imagefs.inodesFree: "3m"
  pid.available: "3m"
...
