---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: repo-github-argocd
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
data: '{{hub copySecretData "rhacm-policies" "repo-github-argocd" hub}}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: repo-github-helm-values
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
data: '{{hub copySecretData "rhacm-policies" "repo-github-helm-values" hub}}'
...
