---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-multicluster-observability            # prefix Application name with 00 for sorting purpose
  namespace: openshift-gitops
  labels:
    applications: multicluster-observability
spec:
  project: gitops
  source:
    repoURL: https://github.com/bkkhoo/argocd.git
    targetRevision: main
    path: helm-charts/rhacm
    helm:
      valuesObject:
        deploymentType: mco
  destination:
    name: in-cluster
    namespace: open-cluster-management-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: env
      value: prod
    - name: type
      value: app
    - name: target
      value: in-cluster
...
