---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-global-hub-operator-rh
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  name: multicluster-global-hub-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: release-1.7
  installPlanApproval: Automatic
  # config:
  #   nodeSelector:
  #     node-role.kubernetes.io/infra: ""
  #   tolerations:
  #     - effect: NoSchedule
  #       key: node-role.kubernetes.io/infra
  #       value: reserved
  #     - effect: NoExecute
  #       key: node-role.kubernetes.io/infra
  #       value: reserved
...
