:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= Bootstrap Hub Cluster

The link:ansible/bootstrap.yaml[Ansible playbook] deploys and configures OpenShift GitOps, RHACM, and Multicluster Global Hub.

The Ansible playbook also creates secrets in the `rhacm-policies` namespace using the link:ansible/templates/[templates in this folder]. The `config-sync-global-hub-secrets` RHACM governance policy sync these secrets (with `rhacm-policies/sync-hub-secret: "yes"` label on `rhacm-policies` namespace) from the global hub to managed hubs, according to the `env` label.

The Ansible playbook bootstrap an OpenShift cluster for the following use cases.

== MultiCluster Global Hub Use Case (Global Hub -> Managed Hubs -> Managed Clusters)

Deploys OpenShift GitOps, RHACM, and Multicluster Global Hub.

[source,bash]
----
ansible-playbook -i localhost, bootstrap/ansible/bootstrap.yaml -e config=ha -e global_hub=yes
----

== Regular RHACM Use Case (Managed Hubs -> Managed Clusters)

Deploys OpenShift GitOps and RHACM.

`dev` env:

[source,bash]
----
ansible-playbook -i localhost, bootstrap/ansible/bootstrap.yaml -e config=basic -e global_hub=no -e env=dev
----

`uat` env:

[source,bash]
----
ansible-playbook -i localhost, bootstrap/ansible/bootstrap.yaml -e config=ha -e global_hub=no -e env=uat
----

`prod`` env:

[source,bash]
----
ansible-playbook -i localhost, bootstrap/ansible/bootstrap.yaml -e config=ha -e global_hub=no -e env=prod
----
