:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= Bootstrap Hub Cluster

The link:ansible/bootstrap.yaml[Ansible playbook] deploys and configures OpenShift GitOps, RHACM, and Multicluster Global Hub. The playbook also create the following secrets in the `rhacm-policies` namespace:

- link:ansible/templates/argocd-repo-secret.yaml.j2[ArgoCD Repository secrets] using the tokens from the link:ansible/vars/github-token-vault-encrypted.yaml[vault-encrypted file].
- link:ansible/templates/openshift-logging-token.yaml.j2[OpenShift Logging HTTP authentication bearer tokens] using the tokens from the link:ansible/vars/openshift-logging-token-encrypted.yaml[vault-encrypted file].

Ansible playbook to bootstrap a new cluster for:

- MultiCluster Global Hub Use Case:
** Deploys OpenShift GitOps, RHACM, and Multicluster Global Hub.
+
[source,bash]
----
ansible-playbook -i localhost, bootstrap/ansible/bootstrap.yaml -e config=basic -e global_hub=yes
----

- Regular RHACM Use Case:
** Deploys OpenShift GitOps and RHACM:
+
*** dev env:
+
[source,bash]
----
ansible-playbook -i localhost, bootstrap/ansible/bootstrap.yaml -e config=basic -e global_hub=no -e env=dev
----

*** uat env:
+
[source,bash]
----
ansible-playbook -i localhost, bootstrap/ansible/bootstrap.yaml -e config=basic -e global_hub=no -e env=uat
----

*** prod env:
+
[source,bash]
----
ansible-playbook -i localhost, bootstrap/ansible/bootstrap.yaml -e config=basic -e global_hub=no -e env=prod
----
