---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-app-of-apps            # prefix Application name with 00 for sorting purpose
  namespace: openshift-gitops
spec:
  project: iac-gitops
  source:
    repoURL: https://github.com/bkkhoo/argocd.git
    path: root-app/managed-cluster/dev
    targetRevision: main
  destination:
    name: in-cluster
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
