---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-logging
  namespace: openshift-logging
  labels:
    applications: openshift-logging
spec:
  goTemplate: true                     # enable go templating for spec.template field
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters:                        # on global-hub, deploy to all clusters except those with managed-hub label
        selector:                      # on managed-hubs, no cluster should have the managed-hub label
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
  template:
    metadata:
      name: "{{ .name }}-openshift-logging"
      labels:
        applications: openshift-logging
    spec:
      project: gitops
      sources:
        - repoURL: https://github.com/bkkhoo/helm-values.git
          targetRevision: main
          path: openshift-logging
          ref: helmValues       # for referencing value files from git source
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: helm-charts/openshift-logging
          helm:
            valuesObject:
              clusterName: '{{ or (index .metadata.labels "cluster-name") null }}'
              env: '{{ or (index .metadata.labels "env") "prod" }}'
              sector: '{{ or (index .metadata.labels "sector") null }}'
            valueFiles:
              # referencing values from git repo source[0].ref above
              # even though source[0].ref.path is specified, the $helmValues still represents the root of the source with ref field
              - '$helmValues/openshift-logging/values.yaml'
      destination:
        server: "{{ .server }}"
        namespace: openshift-logging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true          # do not delete the resources when they are no longer defined in git
        syncOptions:
          - CreateNamespace=true
      info:
        - name: env
          value: any
        - name: type
          value: applicationSet
        - name: target
          value: any openshift clusters
...
