---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gh-config-policy
policyDefaults:
  namespace: rhacm-policies
  policyAnnotations:
    generated-by: policy-generator
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  standards:
    - NIST SP 800-53
  categories:
    - CM Configuration Management
  controls:
    - CM-02 Baseline Configuration
  remediationAction: enforce
  policySets: []
    # - gh-config-managed-hubs
  severity: medium
policySets:
  - name: gh-config-local-cluster
    description: global hub config policies for local-cluster
    placement:
      labelSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - local-cluster
  # - name: gh-config-managed-hubs
  #   description: global hub config policies for all managed hubs
  #   placement:
  #     labelSelector:
  #       matchExpressions:
  #         - key: managed-hub
  #           operator: Exists
  - name: gh-config-dev-hubs
    description: global hub config policies for all dev hubs
    placement:
      labelSelector:
        matchExpressions:
          - key: managed-hub
            operator: Exists
          - key: env
            operator: In
            values:
              - dev
  - name: gh-config-uat-hubs
    description: global hub config policies for all uat hubs
    placement:
      labelSelector:
        matchExpressions:
          - key: managed-hub
            operator: Exists
          - key: env
            operator: In
            values:
              - uat
  - name: gh-config-prod-hubs
    description: global hub config policies for all prod hubs
    placement:
      labelSelector:
        matchExpressions:
          - key: managed-hub
            operator: Exists
          - key: env
            operator: In
            values:
              - prod
placementBindingDefaults:
  name: gh-config-binding

policies:
  - name: config-sync-secrets-dev-hub
    description: sync global hub secrets to dev hubs
    policySets:         # override policyDefaults.policySets
      - gh-config-dev-hubs
    manifests:
      - path: config/sync-secret/dev-hub-sync-secret.yaml

  - name: config-sync-secrets-uat-hub
    description: sync global hub secrets to uat hubs
    policySets:         # override policyDefaults.policySets
      - gh-config-uat-hubs
    manifests:
      - path: config/sync-secret/uat-hub-sync-secret.yaml

  - name: config-sync-secrets-prod-hub
    description: sync global hub secrets to prod hubs
    policySets:         # override policyDefaults.policySets
      - gh-config-prod-hubs
      # should only have one local-cluster (which is the global-hub), which is also a hub; global-hub is a prod cluster
      - gh-config-local-cluster
    manifests:
      - path: config/sync-secret/prod-hub-sync-secret.yaml

  # - name: config-sync-global-hub-secrets
  #   description: sync global hub secrets to managed hubs
  #   policySets:         # override policyDefaults.policySets
  #     - gh-config-local-cluster  # local-cluster of the global-hub is also a managed hub
  #     - gh-config-managed-hubs
  #   manifests:
  #     - path: config/global-hub-secrets/dict.yaml
  #     - path: config/global-hub-secrets/list.yaml
...
