---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gh-monitor-policy
policyDefaults:
  namespace: rhacm-policies
  policyAnnotations:
    generated-by: policy-generator
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  standards:
    - NIST SP 800-53
  categories:
    - CA Assessment Authorization and Monitoring
  controls:
    - CA-07 Continuous Monitoring
  remediationAction: inform
  severity: medium
  policySets:
    - gh-monitor-local-cluster
    - gh-monitor-managed-hubs
policySets:
  - name: gh-monitor-local-cluster
    description: global hub monitor policies for local-cluster
    placement:
      labelSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - local-cluster
  - name: gh-monitor-managed-hubs
    description: global hub monitor policies for all managed hubs
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
          - key: managed-hub
            operator: Exists
placementBindingDefaults:
  name: gh-monitor-binding

policies:
  - name: monitor-managed-clusters
    description: monitor managedCluster availability on global hub and managed hubs
    complianceType: mustnothave
    manifests:
      - path: monitor/managed-cluster-status.yaml

  - name: monitor-managed-hubs-local-cluster
    description: monitor managed hub with local-cluster; no managed hub should have local-cluster
    complianceType: mustnothave
    policySets:           # override policyDefaults.policySets
      - gh-monitor-managed-hubs
    manifests:
      - path: monitor/managed-hubs-local-cluster.yaml

  - name: monitor-multicluster-global-hub-agent
    description: monitor multicluster global hub agent
    complianceType: musthave
    policySets:           # override policyDefaults.policySets
      - gh-monitor-managed-hubs
    manifests:
      - path: monitor/multicluster-global-hub-agent-status.yaml

  - name: monitor-openshift-gitops
    description: monitor openshift gitops deployments
    complianceType: musthave       # object-templates-raw sets its own complianceType
    manifests:
      - path: monitor/openshift-gitops/operator-subscription-status.yaml
      - path: monitor/openshift-gitops/deployment-status.yaml
      - path: monitor/openshift-gitops/object-templates-raw-status.yaml
      - path: monitor/openshift-gitops/argocd-status.yaml

  - name: monitor-argocd-application-set
    description: monitor argocd applicationSets
    complianceType: mustnothave
    namespaceSelector:
      include:
        - openshift-gitops
    manifests:
      - path: monitor/application-set-status.yaml

  - name: monitor-rhacs-central
    description: monitor rhacs central and securedClusters deployments
    complianceType: musthave
    manifests:
      - path: monitor/rhacs-central/operator-subscription-status.yaml
      - path: monitor/rhacs-central/deployment-status.yaml

  # - name: 00-monitor-policy-report      # 00- prefix for the policy name for sorting use
  #   description: monitor policy report with failed results
  #   complianceType: "mustnothave"
  #   controls:
  #     - CA-02 Security Assessments
  #   namespaceSelector:
  #     include:
  #       - "*"
  #     exclude:
  #       - "kube-*"
  #       - "openshift*"
  #       - "open-*"
  #       - "multicluster-*"
  #       - default
  #       - default-broker
  #       - disable-insight
  #       - etcd-backup
  #       - gitops-clusters-broker
  #       - hive
  #       - hypershift
  #       - kanative-eventing
  #       - kanative-serving
  #       - rhacm-policies
  #       - rhacs-operator
  #       - stackrox
  #   manifests:
  #     - path: monitor/policy-report.yaml
...
