---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-pipelines
  namespace: openshift-gitops
  labels:
    applications: openshift-pipelines
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters:                        # on global-hub, deploy to all clusters except those with managed-hub label
        selector:                      # on managed-hubs, no cluster should have the managed-hub label
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
            - key: managed-hub
              operator: DoesNotExist
  template:
    metadata:
      name: "{{ name }}-openshift-pipelines"
      labels:
        applications: openshift-pipelines
    spec:
      project: iac-gitops
      source:
        repoURL: https://github.com/bkkhoo/argocd.git
        targetRevision: main
        path: kustomize-deployments/openshift-pipelines/base/
      destination:
        server: "{{ server }}"
        namespace: openshift-operators
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
...
