---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-chart-2.setLabels" .Values.labels | indent 4 }}
...
