:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= Issues

== ArgoCD Application Stuck in Unknown Status (failed to load open api schema)

ArgoCD application failed to sync with the following errors:

[.wrap,source,text]
----
Failed to load live state: failed to get cluster info for "https://kubernetes.default.svc": error synchronizing cache state : failed to load open api schema while syncing cluster cache: error getting openapi resources: SchemaError(github.com/stolostron/cluster-lifecycle-api/clusterview/v1alpha1.UserPermission.status): unknown model in reference: "github.com~1stolostron~1cluster-lifecycle-api~1clusterview~1v1alpha1.UserPermissionStatus"

error synchronizing cache state : failed to load open api schema while syncing cluster cache: error getting openapi resources: SchemaError(github.com/stolostron/cluster-lifecycle-api/clusterview/v1alpha1.UserPermission.status): unknown model in reference: "github.com~1stolostron~1cluster-lifecycle-api~1clusterview~1v1alpha1.UserPermissionStatus"
----

This ArgoCD sync error essentially means that ArgoCD's application controller is trying to build a cache of the cluster's API schemas, but it encountered a broken, malformed, or incompatible Custom Resource Definition (CRD) version installed on the cluster by RHACM.

The issue was likely introduced in RHACM v2.16.3, making ArgoCD v1.20 incompatible with RHACM v2.16, see https://redhat.atlassian.net/browse/ACM-35283.

Until the issue is fixed, the current workaround is to use RHACM v2.15.

== ArgoCD Applications Stuck in Unknown Status (ArgoCD application controller OOMKilled)

The controller cannot determine if the desired state (Git) matches the live state (Cluster), often due to component failures, connectivity issues, or resource conflicts. The most common root causes are a crashed or OOMKilled application controller, Redis downtime, repo-server manifest generation failures, or missing Custom Resource Definitions (CRDs).

**Troubleshooting & Resolution**:

. Check Component Health: Inspect the core ArgoCD components by running:
+
[source,bash]
----
oc -n openshift-gitops get pods
----
. Review Logs: Check the logs for both the application controller and Redis pods.
. Mitigate Controller Issues: If the controller is not processing applications, restart it:
+
[source,bash]
----
oc -n openshift-gitops rollout restart statefulsets/openshift-gitops-application-controller
----
. Handle Redis Downtime: If Redis is unresponsive, restart the Redis component first, followed by the application controller.

**Memory Limit Adjustment**:

By default, the `statefulsets/openshift-gitops-application-controller`` container has `resources.limits.memory` set to 2Gi. When multiple large applications are syncing simultaneously, the container can run out of memory and get OOMKilled. To resolve this, increase the `resources.limits.memory` to 4Gi or more.

== ArgoCD Applications Stuck in Unknown State (cluster added to fast, hub rhacm probably not ready)

[.wrap,source,text]
----
error synchronizing cache state : failed to get server version: failed to get server version: an error on the server ("proxy to anp-proxy-server failed because No agent available") has prevented the request from succeeding
Failed to load live state: failed to get cluster info for "https://cluster-proxy-addon-user.multicluster-engine.svc.cluster.local:9092/prod-cluster01": error synchronizing cache state : failed to get server version: failed to get server version: an error on the server ("proxy to anp-proxy-server failed because No agent available") has prevented the request from succeeding
Failed to load target state: failed to get cluster version for cluster "https://cluster-proxy-addon-user.multicluster-engine.svc.cluster.local:9092/prod-cluster01": failed to get cluster info for "https://cluster-proxy-addon-user.multicluster-engine.svc.cluster.local:9092/prod-cluster01": error synchronizing cache state : failed to get server version: failed to get server version: an error on the server ("proxy to anp-proxy-server failed because No agent available") has prevented the request from succeeding
----

Likely due to Hub cluster RHACM (`multicluster-engine/cluster-proxy-addon-user` deployment) is not ready when spoke cluster is added.

resolve by restarting the ArgoCD application controller:

[source,bash]
----
oc -n openshift-gitops delete pod -l app.kubernetes.io/name=openshift-gitops-application-controller
----
