---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-compliance
  namespace: openshift-gitops
  labels:
    applications: openshift-compliance
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters: {}     # all clusters
  template:
    metadata:
      name: "{{ name }}-openshift-compliance"
      labels:
        applications: openshift-compliance
    spec:
      project: iac-gitops
      source:
        repoURL: https://github.com/bkkhoo/argocd.git
        targetRevision: main
        path: kustomize-deployments/openshift-compliance/base/
      destination:
        server: "{{ server }}"
        namespace: openshift-compliance
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
...
