---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .Values.lokiStack.name }}
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  managementState: Managed
  tenants:
    mode: openshift-logging
  limits:
    global:
      queries:
        queryTimeout: 3m
      retention:
        days: {{ .Values.lokiStack.retentionDays }}
  storage:
    schemas:
      - version: {{ .Values.lokiStack.schemaVersion }}
        effectiveDate: "2020-10-11"
    secret:
      name: {{ .Values.lokiStack.objectStorage.secret }}
      type: {{ .Values.lokiStack.objectStorage.type }}
    tls:
      caName: openshift-service-ca.crt
      caKey: service-ca.crt
  hashRing:
    type: memberlist
  size: {{ .Values.lokiStack.size }}
  storageClassName: {{ .Values.lokiStack.storageClassName }}
...
