---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Values.lokiStack.objectStorage.secret }}-obc
  namespace: {{ .Values.lokistack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  generateBucketName: {{ .Values.lokiStack.objectStorage.secret }}
  storageClassName: {{ .Values.lokiStack.objectStorage.storageClassName }}
...
