---
cribl:
  org_id: <organization-id>
  workspace: <workspace-name>
  worker_group: <workgroup-name>
  client_id: <client-id>
  client_secret: <client-secret>

loki_stack_url:
  application: <lokistack-endpoint-application-logs>
  infrastructure: <lokistack-endpoint-infrastructure-logs>
  audit: <lokistack-endpoint-audit-logs>

openshift_s3:
  endpoint: <endpoint-url>
  api_key: <access-key-id>
  secret_key: <secret-access-key>

prometheus_rw_token: <prometheus-read-write-token>
...
