---
advertisementMode: l2        # l2 or bgp
ipAddressRanges: []
nodeSelector:                # one or more labels
  node-role.kubernetes.io/worker: ""

#### bgp example
# bgp:
#   myASN: 64512
#   peerASN: 64511
#   routerID: 10.113.118.113
#   keepaliveTime: 30s
#   holdTime: 90s
#   ebgpMultiHop: false
#   aggregationLength: 29
#   communities:
#     - 65535:65281           # NO_EXPORT
#     - 65535:65282           # NO_ADVERTISE
#   peers:
#     - peerAddress: 10.10.10.30
#       peerPort: 1793
#     - peerAddress: 10.10.10.31
#       peerPort: 1793
#   bfd:
#     receiveInterval: 300    # milliseconds
#     transmitInterval: 300   # milliseconds
...
