---
advertisementMode: l2        # l2 or bgp
ipAddressRanges: []
nodeSelector:                # one or more labels
  node-role.kubernetes.io/worker: ""

#### bgp example
# bgp:
#   myASN: 64513
#   peerASN: 64512
#   routerID: 10.10.10.13
#   keepaliveTime: 30s
#   holdTime: 90s
#   ebgpMultiHop: false
#   aggregationLength: 29
#   communities:
#     - 65535:65281           # NO_EXPORT
#     - 65535:65282           # NO_ADVERTISE
#   peers:
#     - peerAddress: 10.118.11.1
#       peerPort: 179
#     - peerAddress: 10.118.11.2
#       peerPort: 179
...
