:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= OpenShift Logging

The Red Hat OpenShift Logging Operator orchestrates log collection and forwarding to Red Had managed log stores and other third-party receivers.

The Helm chart installs the OpenShift Logging operator and configures the ClusterLogForwarder to forward application, infrastructure, and audit log records to an HTTP endpoint using the POST method. It also configures the ClusterLogForwarder to authenticate with the HTTP endpoint using a bearer token stored in a Kubernetes Secret. Administrators must create this secret either:

- manually for each cluster, or
- automatically via the RHACM hub template function.

== Installing the Chart

To install the chart:

[source,bash]
----
helm install --name openshift-logging helm-chart/openshift-logging
----

== Uninstalling the Chart

To uninstall/delete the chart deployment:

[source,bash]
----
helm delete openshift-logging
----

== Configuration

The following table lists the configurable parameters/values of this Helm chart and their default values.

[cols="2,2,4", options="header"]
|===
| Parameter
| Default
| Description

| resources.limits.cpu
| 6
| The maximum CPU resource the collector pod is allowed to consume; exceeding this limit results in throttling.

| resources.limits.memory
| 2Gi
| The maximum memory resource the collector pod is allowed to consume; exceeding this limit results in an Out-Of-Memory (OOM) kill, terminating the container.

| resources.requests.cpu
| 500m
| The minimum CPU resource the collector pod needs to run.

| resources.requests.memory
| 64Mi
| The minimum CPU resource the collector pod needs to run.

| serviceAccount
| log-collector
| Name of the ServiceAccount to use to deploy the Forwarder.

| outputs.httpTimeout
| N/A
| The HTTP request timeout in seconds.

| outputs.insecureSkipVerify
| false
| Disable server certificate verification.

| outputs.__<logType>__
| N/A
| Type of logs, must be one of `application`, `infrastructure`, or `audit`.

| outputs.__<logType>__.url
| N/A
| Endpoint URL for log ingestion.

| outputs.__<logType>__.secret.name
| N/A
| Name of the secret containing the bearer token for authentication.

| outputs.__<logType>__.secret.key
| N/A
| Name of the key used to retrieve the value from the referenced secret.
|===

== Misc

=== Logging to Cribl.Cloud

1. Create API Credential on Cribl UI:

** Click **Cribl** on the top left corner of the UI.
** Click **API Credential** from the side menu.
** Click **Add Credential**.

1. Get API token:
+
[source,bash]
----
export CRIBL_API_TOKEN=$(
curl -X POST 'https://login.cribl.cloud/oauth/token' \
  --header 'Content-Type: application/json' \
  --data '
{
  "grant_type": "client_credentials",
  "client_id": "<client-id>",
  "client_secret": "<client-secret>",
  "audience": "https://api.cribl.cloud"
}' | jq -r .access_token)
----

1. Get Organization ID:

** Click **Organization** from the side menu.
+
[source,bash]
----
export ORG_ID="stoic-gauss-qcj0f23"
export WORKSPACE="main"
----

1. Optionally, get CA certificate for Cribl.Cloud:
+
[source,bash]
----
curl https://i.pki.goog/r1.pem > cribl-stream-ca.crt
curl https://i.pki.goog/wr1.pem >> cribl-stream-ca.crt
----
+
[NOTE]
====
Generally users do not need to download CA certificate for Cribl.Cloud manually because Cribl.Cloud uses Google Trust Services (GTS) as its Certificate Authority.

To manually download the required certificates:

- visit link:https://pki.goog/repository/[Google Trust Services Root Repository].
- download the GTS Root R1 certificate in PEM format.
- download the WR1 intermediate certificate in PEM format.
====

1. Configure HTTP data source:
+
[source,bash]
----
curl -X POST \
  --header "Authorization: Bearer ${CRIBL_API_TOKEN}" \
  --header "Content-Type: application/json" \
  --date @files/cribl-data-source.json \
  https://${WORKSPACE}-${ORG_ID}.cribl.cloud/api/v1/m/default/system/inputs
----

curl -X POST \
  --header "Authorization: Bearer ${CRIBL_API_TOKEN}" \
  --header "Content-Type: application/json" \
  --date @~/git-repos/argocd/helm-charts/openshift-logging/files/cribl-data-source-with-tokens.json \
  https://${WORKSPACE}-${ORG_ID}.cribl.cloud/api/v1/m/default/system/inputs
