---
resources:
  limits:
    cpu: "6"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 64Mi
serviceAccount: log-collector
outputs:
  httpTimeout: 10
  application:
    url: "https://application.log-receiver.svc:8443/log"
    secret:
      name: openshift-logging-bearer-tokens     # rhacm policy will create this secret
      key: application
  infrastructure:
    url: "https://infrastructure.log-receiver.svc:8443/log"
    secret:
      name: openshift-logging-bearer-tokens
      key: infrastructure
  audit:
    url: "https://audit.log-receiver.svc:8443/log"
    secret:
      name: openshift-logging-bearer-tokens
      key: audit
...
