---
resources:
  limits:
    cpu: "6"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 64Mi
serviceAccount: log-collector
# outputs:
#   httpTimeout: 10
#   application:
#     url: "https://application-logs.example.com"
#     secret:
#       name: app-log-token
#       key: token
#   infrastructure:
#     url: "https://infrastructure-logs.example.com"
#     secret:
#       name: infra-log-token
#       key: token
#   audit:
#     url: "https://audit-logs.example.com"
#     secret:
#       name: audit-log-token
#       key: token
...
