{{- if has .Values.deploymentType (list "central" "all") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-sync-hook
  namespace: {{ .Values.namespace.central }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
data:
  create-crs.sh: |
{{ .Files.Get "scripts/create-crs.sh" | indent 4 }}
...
{{- end }}
