{{- if has .Values.deploymentType (list "central" "all") }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-crs
  namespace: {{ .Values.namespace.central }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  activeDeadlineSeconds: 600      # max duration the job is allowed to run
  template:
    spec:
      containers:
        - name: create-crs
          image: {{ .Values.postSyncHookImage.name }}:{{ .Values.postSyncHookImage.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - /scripts/create-crs.sh
          env:
            - name: RHACS_CENTRAL_NAMESPACE
              value: {{ .Values.namespace.central }}
            - name: RHACM_POLICIES_NAMESPACE
              value: {{ .Values.namespace.rhacmPolicies }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: rhacs-admin-password
              mountPath: /var/run/secrets/rhacs
      volumes:
        - name: scripts
          configMap:
            name: rhacs-post-sync-hook
            defaultMode: 0755
        - name: rhacs-admin-password
          secret:
            secretName: central-htpasswd
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: rhacs-post-sync-hook
      terminationGracePeriodSeconds: 30
...
{{- end }}
