{{- if eq .Values.deploymentType "central" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-sync-hook
  namespace: {{ .Values.namespace.central }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-sync-hook
  namespace: {{ .Values.namespace.rhacmPolicies }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
...
{{- end }}
