# using ApplicationSet instead of Application since Application does not support syncPolicy.preserveResourcesOnDeletion
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhacm-policies
  namespace: openshift-gitops
  labels:
    applications: rhacm-policies
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - list:                            # list of 1 element
        elements:
          - name: in-cluster
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: "00-rhacm-policies"        # prefix Application name with 00 for sorting purpose
      labels:
        applications: rhacm-policies
    spec:
      project: iac-gitops
      source:
        repoURL: https://github.com/bkkhoo/argocd.git
        targetRevision: main
        path: rhacm-policies/base
      destination:
        server: "{{ server }}"
        namespace: rhacm-policies
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
...
