---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-rhacm-policies
  namespace: openshift-gitops
  labels:
    applications: rhacm-policies
spec:
  project: iac-gitops
  source:
    repoURL: https://github.com/bkkhoo/argocd.git
    targetRevision: main
    path: rhacm-policies/base
  destination:
    name: in-cluster
    namespace: rhacm-policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    info:
      - name: env
        value: any
      - name: type
        value: application
      - name: target
        value: in-cluster
...
