{{- if has .Values.deploymentType (list "mco" "operator+mco" "all") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-sync-hook
  namespace: {{ .Values.observability.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "205"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: observability-sync-hook
  namespace: {{ .Values.observability.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "205"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    resourceNames:
      - {{ .Values.observability.objectStorage.name }}-obc
      - {{ .Values.observability.objectStorage.name }}
      - openshift-service-ca.crt
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:       # cannot restrict create requests by resourceNames
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ .Values.observability.objectStorage.name }}
      - {{ .Values.observability.objectStorage.caSecret }}
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observability-sync-hook
  namespace: {{ .Values.observability.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "205"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: observability-sync-hook
subjects:
  - kind: ServiceAccount
    name: observability-sync-hook
    namespace: {{ .Values.observability.namespace }}
...
{{- end }}
