---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: gitops-plugin
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backend:
    service:
      basePath: /
      name: gitops-plugin
      namespace: openshift-gitops
      port: 9001
    type: Service
  displayName: GitOps Plugin
  i18n:
    loadType: Preload
...
