---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-stack-sync-hook
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
data:
  create-s3-secret.sh: |
{{ .Files.Get "files/create-s3-secret.sh" | indent 4 }}
...
