---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-stack-sync-hook
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-stack-sync-hook
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    resourceNames:
      - {{ .Values.lokiStack.objectStorage.secret }}-obc
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:       # cannot restrict create requests by resourceNames
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ .Values.lokiStack.objectStorage.secret }}
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-stack-sync-hook
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-stack-sync-hook
subjects:
  - kind: ServiceAccount
    name: loki-stack-sync-hook
    namespace: {{ .Values.lokiStack.namespace }}
...
