{{- if has .Values.deploymentType (list "mco" "operator+mco" "all") }}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Values.observability.objectStorage.name }}-obc
  namespace: {{ .Values.observability.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  generateBucketName: {{ .Values.observability.objectStorage.name }}-bucket
  storageClassName: {{ .Values.observability.objectStorage.storageClassName }}
...
{{- end }}
