{{- if has .Values.deploymentType (list "secured-cluster" "all") }}
  {{- if not (and (eq .Values.deploymentType "all") (eq .Values.namespace.central .Values.namespace.securedCluster)) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.securedCluster }}
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec: {}
...
  {{- end }}
{{- end }}
