{{- if eq .Values.deploymentType "secured-cluster" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.securedCluster }}
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec: {}
...
{{- end }}
