# the following policies are disabled on managed hubs because managed hubs do not manage themselves and lack a local-cluster:
#   config-argocd-repo-secrets: this policy is only for distributed argocd repo secrets from global-hub to managed-hubs
#   monitor-managed-clusters: ManagedClusters only appeared on local-cluster
#   monitor-managed-hubs-local-cluster
#   monitor-rhacs-central: rhacs central is only deployed on local-cluster
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: 00-rhacm-policies
    patch: |
      - op: replace
        path: /spec/source/path
        value: rhacm-policies/overlays/managed-hub
...
