# on managed hubs, the following resources are disable:
# - policy:
#   - monitor-managed-clusters: no local-cluster on managed hub, ManagedClusters only appeared on local-cluster
#   - monitor-managed-hubs-no-local-cluster: this policy ony applicable to global-hub
#   - monitor-rhacs-central: no local-cluster on managed hub, rhacs central is only deployed on local-cluster
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: 00-rhacm-policies
    patch: |
      - op: add
        path: /spec/source/kustomize
        value:
          patches:
            - target:
                group: policy.open-cluster-management.io
                version: v1
                kind: Policy
                name: monitor-managed-clusters
              patch: |
                - op: replace
                  path: /spec/disabled
                  value: true
            - target:
                group: policy.open-cluster-management.io
                version: v1
                kind: Policy
                name: monitor-managed-hubs-no-local-cluster
              patch: |
                - op: replace
                  path: /spec/disabled
                  value: true
            - target:
                group: policy.open-cluster-management.io
                version: v1
                kind: Policy
                name: monitor-rhacs-central
              patch: |
                - op: replace
                  path: /spec/disabled
                  value: true
...
