:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= Advanced Cluster Management for Kubernetes - Import Cluster

Apply the manifests generated by this Helm chart to import Kubernetes-based cluster into RHACM hub.

== Installing the Chart

Import/Attach cluster to RHACM hub:

. Create a `values.yaml` file locally:
+
[source,yaml]
----
cat << EOF > /tmp/values.yaml
clusterName: <cluster-name>
clusterURL: <https-url>
clusterAuthToken: <token>
clusterSet: gitops-clusters
clusterLabels:
  env: dev
  managed-hub: "yes"
EOF
----
+
[NOTE]
====
- The label selector uses the `Exists` or `DoesNotExist` operator on `clusterLabels.managed-hub` label, which verifies the label's presence regardless of its value.
- If the value of the `clusterLabels.managed-hub` label is a boolean, it must be quoted. Unquoted boolean values will result in the following error:

[source,bash]
----
unable to decode "STDIN": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.labels of type string
Error from server (Invalid): error when creating "STDIN": KlusterletAddonConfig.agent.open-cluster-management.io "dev-hub01" is invalid: spec.clusterLabels.managed-hub: Invalid value: "boolean": spec.clusterLabels.managed-hub in body must be of type string: "boolean"
----
====

. Apply the Helm chart:
+
[source,bash]
----
helm template helm-charts/rhacm-import-cluster/ --values /tmp/values.yaml | oc apply -f -
----
+
[NOTE]
====
The step uses `helm template` to generate the manifests and apply them to OpenShift, instead of `helm install`.
====

. Clean up
+
[source,bash]
----
rm /tmp/values.yaml
----

== Configuration

The following table lists the configurable parameters/values of this Helm chart and their default values.

[cols="2,1,4", options="header"]
|===
| Parameter
| Default
| Description

| clusterName
| None
| Name of the cluster.

| clusterURL
| None
| URL of the cluster.

| clusterAuthToken
| None
| Bearer token with cluster admin privileges from the cluster.

| clusterLabels
| None
| Additional labels to apply to the cluster.
|===
