:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= Configure OpenShift Monitoring

Configure the preinstalled OpenShift Monitoring stack.

== Installing the Chart

To install the chart:

[source,bash]
----
helm install --name openshift-monitoring helm-chart/openshift-monitoring
----

== Configuration

The following table lists the configurable parameters/values of this Helm chart and their default values.

[cols="2,1,4", options="header"]
|===
| Parameter
| Default
| Description

| enableUserWorkload
| true
| Enable/Disable user workload monitoring in OpenShift.

| storageClass
| None
| Assign specific storage class for OpenShift monitoring components' persistent volumes.

| platform.prometheusK8s.retention
| 7d (7 days)
| Define data retention time to prevent indefinite storage growth for the Prometheus instance responsible for monitoring core OpenShift platform component.

| platform.prometheusK8s.storage
| 20Gi
| Define specific storage resource requests for persistent volumes of the Prometheus instance responsible for monitoring core OpenShift platform component.

| platform.alertmanagerMain.storage
| 10Gi
| Define specific storage resource requests for persistent volumes of the default Alertmanager instance.

| userWorkload.prometheus.retention
| 24h (24 hours)
| Define data retention time to prevent indefinite storage growth for the Prometheus instance responsible for monitoring user workloads.

| userWorkload.prometheus.storage
| 10Gi
| Define specific storage resource requests for persistent volumes of the Prometheus instance responsible for monitoring user workloads.

| userWorkload.thanosRuler.retention
| 24h (24 hours)
| Define data retention time to prevent indefinite storage growth for the Thanos Ruler instance responsible for monitoring user workloads.

| userWorkload.thanosRuler.storage
| 10Gi
| Define specific storage resource requests for persistent volumes of the Thanos Ruler instance responsible for monitoring user workloads.
|===

== Interaction with RHACM Multi Cluster Observability

When Red Hat Advanced Cluster Management (RHACM) enables the observability service (MultiClusterObservability) on OpenShift clusters, the observability endpoint operator automatically creates or updates (merges) the openshift-monitoring ConfigMaps (`cluster-monitoring-config` in `openshift-monitoring` namespace and `user-workload-monitoring-config` in `openshift-user-workload-monitoring` namespace) to include additional configuration:

[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    nodeExporter:
      collectors:
        buddyinfo: {}
        cpufreq: {}
        ksmd: {}
        mountstats: {}
        netclass: {}
        netdev: {}
        processes: {}
        systemd: {}
        tcpstat: {}
    prometheusK8s:
      additionalAlertmanagerConfigs:
      - apiVersion: v2
        bearerToken:
          key: token
          name: observability-alertmanager-accessor-a8579bd428b74b80b63
        scheme: https
        staticConfigs:
        - alertmanager-open-cluster-management-observability.apps.cluster-rvsq9.dyn.redhatworkshops.io
        tlsConfig:
          ca:
            key: service-ca.crt
            name: hub-alertmanager-router-ca-a8579bd428b74b80b63
          insecureSkipVerify: false
      externalLabels:
        managed_cluster: 724b1219-4b4c-4a72-9b78-e9058050796c
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      additionalAlertmanagerConfigs:
      - apiVersion: v2
        bearerToken:
          key: token
          name: observability-alertmanager-accessor-a8579bd428b74b80b63
        scheme: https
        staticConfigs:
        - alertmanager-open-cluster-management-observability.apps.cluster-rvsq9.dyn.redhatworkshops.io
        tlsConfig:
          ca:
            key: service-ca.crt
            name: hub-alertmanager-router-ca-a8579bd428b74b80b63
          insecureSkipVerify: false
----

The additional configuration above would cause the link:../../apps/openshift-monitoring/[openshift-monitoring ArgoCD application] to become **OutOfSync**, as the link:./templates/configmap.yaml[manifests pushed by the ArgoCD application] differ from the fields injected by the observability endpoint operator.

To prevent the openshift-monitoring ArgoCD application from entering an **OutOfSync** state, add the following annotation to the openshift-monitoring ConfigMaps:

[source,yaml]
----
annotations:
  argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
----

And includes the following `ignoreDifferences` configuration to the openshift-monitoring ArgoCD application:
[source,yaml]
----
ignoreDifferences:
  - group: ""
    kind: ConfigMap
    name: cluster-monitoring-config
    namespace: openshift-monitoring
    managedFieldsManagers:
      - endpoint-monitoring-operator
  - group: ""
    kind: ConfigMap
    name: user-workload-monitoring-config
    namespace: openshift-user-workload-monitoring
    managedFieldsManagers:
      - endpoint-monitoring-operator
----
