---
enableUserWorkload: true
# storageClass: gp3-csi
platform:
  prometheusK8s:
    retention: 7d              # default 15d
    storage: 20Gi
  alertManager:
    storage: 10Gi
userWorkload:
  prometheus:
    retention: 24h             # default 4h
    storage: 10Gi
  thanosRuler:
    retention: 24h              # default 24h
    storage: 10Gi
...
