---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../../../apps/rhacs-central/dev
  - ../../../apps/openshift-web-terminal/base
  # - ../../../apps/openshift-compliance/base
  - ../../../apps/rhacs-secured-cluster/dev
  # - ../../../apps/test1/dev
...
