---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-gitops-operator-controller-manager
  namespace: openshift-gitops-operator
  labels:
    olm.owner: '{{ (lookup "operators.coreos.com/v1alpha1" "Subscription" "openshift-operators-operator" "openshift-gitops-operator").status.currentCSV }}'
status:
  conditions:
    - status: "True"
      type: Available
...
