---
object-templates-raw: |
  {{- $argocd := lookup "argoproj.io/v1beta1" "ArgoCD" "openshift-gitops" "openshift-gitops" }}
  {{- $deployment_name := "" }}
  {{- if $argocd.spec.ha.enabled }}
    {{- $deployment_name = "openshift-gitops-redis-ha-haproxy" }}
  {{- else }}
    {{- $deployment_name = "openshift-gitops-redis" }}
  {{- end }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: {{ $deployment_name }}
        namespace: openshift-gitops
      status:
        conditions:
          - status: "True"
            type: Available
...
