---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: insights-post-sync-hook
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: insights-post-sync-hook
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: insights-post-sync-hook
subjects:
  - kind: ServiceAccount
    name: insights-post-sync-hook
    namespace: default
...
