---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mandatory-operators
  namespace: openshift-gitops
  labels:
    applications: mandatory-operators
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters:                        # on global-hub, deploy to all clusters except those with managed-hub label
        selector:                      # on managed-hubs, no cluster should have the managed-hub label
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
            - key: managed-hub
              operator: DoesNotExist
    # argocd automatically registers the local cluster (in-cluster) as https://kubernetes.default.svc but does not create a Secret for
    # it by default, meaning it lacks the "argocd.argoproj.io/secret-type: cluster" label; consequently, selectors like matchExpressions
    # and matchLabels will exclude the local cluster. the list generator below include local cluster int the selection.
    - list:
        elements:
          - name: in-cluster
            server: https://kubernetes.default.svc
            metadata:
              labels:
                env: prod
  template:
    metadata:
      name: "{{ name }}-mandatory-operators"
      labels:
        applications: mandatory-operators
    spec:
      project: gitops
      sources:
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: helm-charts/openshift-logging/
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/openshift-pipelines/base/
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: helm-charts/openshift-compliance/
          helm:
            valuesObject:
              complianceScan:
                enable: false
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/openshift-web-terminal/base/
      destination:
        server: "{{ server }}"
        namespace: default
      ignoreDifferences:
        - group: compliance.openshift.io      # the ScanSetting schedule has random values
          kind: ScanSetting
          name: raw-result-on-worker
          jsonPointers:
            - /schedule
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      info:
        - name: env
          value: any
        - name: type
          value: applicationSet
        - name: target
          value: in-cluster and clusters without managed-hub label
...
