---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-log-token
  namespace: openshift-logging
data:
  token: '{{hub fromSecret "rhacm-policies" "openshift-logging-token" "application" hub}}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: infra-log-token
  namespace: openshift-logging
data:
  token: '{{hub fromSecret "rhacm-policies" "openshift-logging-token" "infrastructure" hub}}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: audit-log-token
  namespace: openshift-logging
data:
  token: '{{hub fromSecret "rhacm-policies" "openshift-logging-token" "audit" hub}}'
...
