---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
status:
  sync:
    status: Unknown
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
status:
  sync:
    status: OutOfSync
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
status:
  health:
    status: Unknown
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
status:
  health:
    status: Missing
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
status:
  health:
    status: Degraded
...
