---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
status:
  conditions:
    - type: Available
      status: "False"
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
status:
  conditions:
    - type: Degraded
      status: "True"
...
