# copy argocd repo secret (secret with "argocd.argoproj.io/secret-type: repository" label) from global-hub to managed-hubs
---
object-templates-raw: |
  {{hub range (lookup "v1" "Secret" "rhacm-policies" "" "argocd.argoproj.io/secret-type=repository").items hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: {{hub .metadata.name hub}}
        namespace: openshift-gitops
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        {{hub range $key, $value := .data hub}}
        {{hub $key hub}}: {{hub $value hub}}
        {{hub end hub}}
  {{hub end hub}}
...
