:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= OpenShift Service Mesh 2

Red Hat OpenShift Service Mesh provides an easy way to create a network of deployed services that provides discovery, load balancing, service-to-service authentication, failure recovery, metrics, and monitoring. A service mesh also provides more complex operational functionality, including A/B testing, canary releases, rate limiting, access control, and end-to-end authentication.

== Installing the Chart

The install the chart:

[source,bash]
----
helm install --name openshift-compliance helm-chart/openshift-service-mesh-2
----

== Uninstalling the Chart

To uninstall/delete the chart deployment:

[source,bash]
----
helm delete openshift-service-mesh-2
----

== Configuration

The following table lists the configurable parameters/values of this Helm chart and their default values.

[cols="2,1,4", options="header"]
|===
| Parameter
| Default
| Description

| version
| 3
| OpenShift Service Mesh version 2 or 3.
|===
