{{- if .Values.complianceScan.enable }}
---
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: oc4-cis
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
profiles:
{{- range .Values.complianceScan.profiles }}
  - name: {{ . }}
    apiGroup: compliance.openshift.io/v1alpha1
    kind: Profile
{{- end }}
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: raw-result-on-worker               # this store raw result on worker instead of master
...
{{- end }}
