---
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: tailored-ocp4-cis
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  extends: ocp4-cis
  title: Tailored ocp4-cis profile
  description: Tailor ocp4-cis profile, removing rules that will result in MANUAL status
  disableRules:
    - name: ocp4-accounts-restrict-service-account-tokens
      rationale: MANUAL action required
    - name: ocp4-accounts-unique-service-account
      rationale: MANUAL action required
    - name: ocp4-general-apply-scc
      rationale: MANUAL action required
    - name: ocp4-general-default-namespace-use
      rationale: MANUAL action required
    - name: ocp4-general-default-seccomp-profile
      rationale: MANUAL action required
    - name: ocp4-general-namespaces-in-use
      rationale: MANUAL action required
    - name: ocp4-rbac-least-privilege
      rationale: MANUAL action required
    - name: ocp4-rbac-limit-cluster-admin
      rationale: MANUAL action required
    - name: ocp4-rbac-limit-secrets-access
      rationale: MANUAL action required
    - name: ocp4-rbac-pod-creation-access
      rationale: MANUAL action required
    - name: ocp4-rbac-wildcard-use
      rationale: MANUAL action required
    - name: ocp4-scc-drop-container-capabilities
      rationale: MANUAL action required
    - name: ocp4-scc-limit-ipc-namespace
      rationale: MANUAL action required
    - name: ocp4-scc-limit-net-raw-capability
      rationale: MANUAL action required
    - name: ocp4-scc-limit-network-namespace
      rationale: MANUAL action required
    - name: ocp4-scc-limit-privilege-escalation
      rationale: MANUAL action required
    - name: ocp4-scc-limit-privileged-containers
      rationale: MANUAL action required
    - name: ocp4-scc-limit-process-id-namespace
      rationale: MANUAL action required
    - name: ocp4-scc-limit-root-containers
      rationale: MANUAL action required
    - name: ocp4-secrets-consider-external-storage
      rationale: MANUAL action required
    - name: ocp4-secrets-no-environment-variables
      rationale: MANUAL action required
    # - name: ocp4-configure-network-policies-namespaces
    #   rationale: tbd, scan FAIL
    # - name: ocp4-scc-limit-container-allowed-capabilities
    #   rationale: tbd, scan FAIL
---
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: tailored-ocp4-cis-node
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  extends: ocp4-cis-node
  title: Tailored ocp4-cis-node profile
  description: Tailor ocp4-cis-node profile, removing rules that will result in MANUAL status
  disableRules: []
---
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: tailored-ocp4-moderate
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  extends: ocp4-moderate
  title: Tailored ocp4-moderate profile
  description: Tailor ocp4-moderate profile, removing rules that will result in MANUAL status
  disableRules:
    - name: ocp4-accounts-restrict-service-account-tokens
      rationale: MANUAL action required
    - name: ocp4-accounts-unique-service-account
      rationale: MANUAL action required
    - name: ocp4-general-apply-scc
      rationale: MANUAL action required
    - name: ocp4-general-configure-imagepolicywebhook
      rationale: MANUAL action required
    - name: ocp4-general-default-namespace-use
      rationale: MANUAL action required
    - name: ocp4-general-default-seccomp-profile
      rationale: MANUAL action required
    - name: ocp4-general-namespaces-in-use
      rationale: MANUAL action required
    - name: ocp4-rbac-least-privilege
      rationale: MANUAL action required
    - name: ocp4-rbac-limit-cluster-admin
      rationale: MANUAL action required
    - name: ocp4-rbac-limit-secrets-access
      rationale: MANUAL action required
    - name: ocp4-rbac-pod-creation-access
      rationale: MANUAL action required
    - name: ocp4-rbac-wildcard-use
      rationale: MANUAL action required
    - name: ocp4-scc-drop-container-capabilities
      rationale: MANUAL action required
    - name: ocp4-scc-limit-ipc-namespace
      rationale: MANUAL action required
    - name: ocp4-scc-limit-net-raw-capability
      rationale: MANUAL action required
    - name: ocp4-scc-limit-network-namespace
      rationale: MANUAL action required
    - name: ocp4-scc-limit-privilege-escalation
      rationale: MANUAL action required
    - name: ocp4-scc-limit-privileged-containers
      rationale: MANUAL action required
    - name: ocp4-scc-limit-process-id-namespace
      rationale: MANUAL action required
    - name: ocp4-scc-limit-root-containers
      rationale: MANUAL action required
    - name: ocp4-secrets-consider-external-storage
      rationale: MANUAL action required
    - name: ocp4-secrets-no-environment-variables
      rationale: MANUAL action required
    # - name: ocp4-configure-network-policies-namespaces
    #   rationale: tbd, scan FAIL
    # - name: ocp4-file-integrity-exists
    #   rationale: tbd, scan FAIL
    # - name: ocp4-file-integrity-notification-enabled
    #   rationale: tbd, scan FAIL
    # - name: ocp4-fips-mode-enabled-on-all-nodes
    #   rationale: tbd, scan FAIL
    # - name: ocp4-resource-requests-limits-in-deployment
    #   rationale: tbd, scan FAIL
    # - name: ocp4-resource-requests-limits-in-statefulset
    #   rationale: tbd, scan FAIL
    # - name: ocp4-resource-requests-quota
    #   rationale: tbd, scan FAIL
    # - name: ocp4-scc-limit-container-allowed-capabilities
    #   rationale: tbd, scan FAIL

---
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: tailored-ocp4-moderate-node
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  extends: ocp4-moderate
  title: Tailored ocp4-moderate-node profile
  description: Tailor ocp4-moderate-node profile, removing rules that will result in MANUAL status
  disableRules:
    - name: ocp4-partition-for-var-log-kube-apiserver
      rationale: MANUAL action required
    - name: ocp4-partition-for-var-log-oauth-apiserver
      rationale: MANUAL action required
    - name: ocp4-partition-for-var-log-openshift-apiserver
      rationale: MANUAL action required
    # - name: ocp4-directory-access-var-log-kube-audit
    #   rationale: tbd, scan FAIL
    # - name: ocp4-directory-access-var-log-oauth-audit
    #   rationale: tbd, scan FAIL
    # - name: ocp4-directory-access-var-log-ocp-audit
    #   rationale: tbd, scan FAIL
    # - name: ocp4-reject-unsigned-images-by-default
    #   rationale: tbd, scan FAIL
...
