{{- if index .Values "outputs" }}
---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  managementState: Managed
  collector:
    resources:
      limits:
        cpu: "{{ .Values.resources.limits.cpu }}"
        memory: {{ .Values.resources.limits.memory }}
      requests:
        cpu: "{{ .Values.resources.requests.cpu }}"
        memory: {{ .Values.resources.requests.memory }}
  serviceAccount:
    name: {{ .Values.serviceAccount }}
  filters:
    - name: detect-multiline-exception
      type: detectMultilineException
    - name: custom-labels
      type: openshiftLabels
      openshiftLabels:
        cluster_name: {{ .Values.clusterName }}
        env: {{ .Values.env }}
  {{- $outputs := .Values.outputs }}
  outputs:
  {{- range $tenant := list "application" "infrastructure" "audit" }}
    {{- if index $outputs $tenant }}
      {{- $config := index $outputs $tenant }}
    - name: {{ $tenant }}-output
      type: http
      http:
        url: {{ $config.url }}
        method: POST
        format: ndjson
        headers:
          Content-Type: "application/x-ndjson"
        authentication:
          token:
            from: secret
            secret:
              name: {{ $config.secret.name }}
              key: {{ $config.secret.key }}
        timeout: {{ $outputs.httpTimeout }}
        tuning:
          maxWrite: {{ $outputs.tuning.maxWrite | int }}
      tls:
        {{- if $outputs.insecureSkipVerify }}
        insecureSkipVerify: true
        {{- else }}
        ca:
          configMapName: {{ $outputs.ca.configMap }}
          key: {{ $outputs.ca.key }}
        {{- end }}
    {{- end }}
  {{- end }}
  pipelines:
    {{- range $tenant := list "application" "infrastructure" "audit" }}
      {{- if index $outputs $tenant }}
    - name: {{ $tenant }}-pipeline
      filterRefs:
        {{- if ne $tenant "audit" }}
        - detect-multiline-exception
        {{- end }}
        - custom-labels
      inputRefs:
        - {{ $tenant }}
      outputRefs:
        - {{ $tenant }}-output
      {{- end }}
    {{- end }}
...
{{- end }}
