---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
data:
  config.yaml: |
    alertmanagerMain:
      enableUserAlertmanagerConfig: {{ .Values.enableUserWorkload }}
      volumeClaimTemplate:
        metadata: {}
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.platform.alertmanagerMain.storage }}
        status: {}
    enableUserWorkload: {{ .Values.enableUserWorkload }}
    nodeExporter:
      collectors:
        buddyinfo: {}
        cpufreq: {}
        ksmd: {}
        mountstats: {}
        netclass: {}
        netdev: {}
        processes: {}
        systemd: {}
        tcpstat: {}
    prometheusK8s:
      retention: {{ .Values.platform.prometheusK8s.retention }}
      volumeClaimTemplate:
        metadata: {}
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          volumeMode: Filesystem
          resources:
            requests:
              storage: {{ .Values.platform.prometheusK8s.storage }}
        status: {}
{{- if .Values.enableUserWorkload }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
data:
  config.yaml: |
    prometheus:
      retention: {{ .Values.userWorkload.prometheus.retention }}
      volumeClaimTemplate:
        metadata: {}
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.userWorkload.prometheus.storage }}
        status: {}
    thanosRuler:
      retention: {{ .Values.userWorkload.thanosRuler.retention }}
      volumeClaimTemplate:
        metadata: {}
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.userWorkload.thanosRuler.storage }}
        status: {}
{{- end }}
...
