---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true,IgnoreExtraneous
data:
  config.yaml: |
    enableUserWorkload: {{ .Values.enableUserWorkload }}
    prometheusK8s:
      retention: {{ .Values.platform.prometheusK8s.retention }}
      volumeClaimTemplate:
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          volumeMode: Filesystem
          resources:
            requests:
              storage: {{ .Values.platform.prometheusK8s.storage }}
    alertmanagerMain:
      enableUserAlertmanagerConfig: {{ .Values.enableUserWorkload }}
      volumeClaimTemplate:
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.platform.alertmanagerMain.storage }}
{{- if .Values.enableUserWorkload }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true,IgnoreExtraneous
data:
  config.yaml: |
    prometheus:
      retention: {{ .Values.userWorkload.prometheus.retention }}
      volumeClaimTemplate:
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.userWorkload.prometheus.storage }}
    thanosRuler:
      retention: {{ .Values.userWorkload.thanosRuler.retention }}
      volumeClaimTemplate:
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.userWorkload.thanosRuler.storage }}
{{- end }}
...
