---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: {{ .Values.enableUserWorkload }}
    prometheusK8s:
      retention: {{ .Values.platform.prometheusK8s.retention }}
      volumeClaimTemplate:
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          volumeMode: Filesystem
          resources:
            requests:
              storage: {{ .Values.platform.prometheusK8s.storage }}
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.platform.alertManager.storage }}
      enableUserAlertmanagerConfig: {{ .Values.enableUserWorkload }}
{{- if .Values.enableUserWorkload }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      retention: {{ .Values.userWorkload.prometheus.retention }}
      volumeClaimTemplate:
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.userWorkload.prometheus.storage }}
    thanosRuler:
      retention: {{ .Values.userWorkload.thanosRuler.retention }}
      volumeClaimTemplate:
        spec:
          {{- if hasKey .Values "storageClass" }}
          storageClassName: {{ .Values.storageClass }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.userWorkload.thanosRuler.storage }}
{{- end }}
...
