:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= About this Kustomize Deployment

The resources (except namespace.yaml) in this folder are intended for use as ArgoCD PostSync hook. ArgoCD automatically deletes all the resources (except namespace.yaml) created by this deployment immediately after the PostSync hook completes successfully.

When not using ArgoCD, manually delete the resources (except namespace.yaml) after the job completes.

[NOTE]
====
- No overlays are necessary since the configuration is the same for all environments (`dev`, `uat`, or `prod`).
- An ArgoCD application cannot consist solely of a PreSync/PostSync hook without any application resources.
====

== Opting Out of Remote Heath and Usage Data Reporting

Customers can opt out of reporting health and usage data. Red Hat strongly recommends leaving health and usage reporting enabled for pre-production and test clusters even if it is necessary to opt out for production clusters. This allows Red Hat to be a participant in qualifying OpenShift Container Platform in your environments and react more rapidly to product issues.

Some of the consequences of opting out of having a connected cluster are:
- Red Hat will not be able to monitor the success of product upgrades or the health of your clusters without a support case being opened.
- Red Hat will not be able to use configuration data to better triage customer support cases and identify which configurations our customers find important.
- The OpenShift Cluster Manager will not show data about your clusters including health and usage information.
- Your subscription entitlement information must be manually entered via console.redhat.com without the benefit of automatic usage reporting.

[NOTE]
====
- After reporting of health and usage data has been disabled, manually register the cluster to link:https://console.redhat.com/openshift/register[Red Hat Hybrid Cloud Console].
- Use the following command to retrieve the Cluster ID of the cluster:
+
[source,bash]
----
oc get clusterversions.config.openshift.io version -o jsonpath="{.spec.clusterID}"
----
====

== References

- https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/support/remote-health-monitoring-with-connected-clusters#insights-operator-new-pull-secret_remote-health-reporting
- https://manuvaldi.github.io/openshift-disconnected-workshop/openshift-disconnected-workshop/08-Insights-and-Telemetry.html
