---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../../apps/rhacs-central/overlays/dev
  - ../../../../apps/openshift-web-terminal/base
  # - ../../../../apps/openshift-compliance/base
  - ../../../../apps/rhacs-secured-cluster/overlays/dev
  # - ../../../../apps/test1/overlays/dev
...
