{{- if has .Values.deploymentType (list "operator" "operator+mch" "operator+mco" "all") }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rhacmNamespace }}
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec: {}
...
{{- end }}
