{{- if has .Values.deploymentType (list "operator" "operator+mch" "operator+mco" "all") }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management-operator-group
  namespace: {{ .Values.rhacmNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - open-cluster-management
...
{{- end }}
