---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: base-monitor-policy
policyDefaults:
  namespace: rhacm-policies
  policyAnnotations:
    generated-by: policy-generator
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  standards:
    - NIST SP 800-53
  categories:
    - CA Assessment Authorization and Monitoring
  controls:
    - CA-07 Continuous Monitoring
  remediationAction: inform
  severity: medium
  policySets:
    - base-monitor-all-clusters
policySets:
  - name: base-monitor-all-clusters
    description: monitoring policies for all clusters
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
  - name: base-monitor-metallb
    description: monitoring policies for clusters with metallb deployed
    placement:
      labelSelector:
        matchExpressions:
          - key: metallb
            operator: Exists
  - name: base-monitor-openshift-serverless
    description: monitoring policies for clusters with openshift-serverless deployed
    placement:
      labelSelector:
        matchExpressions:
          - key: openshift-serverless
            operator: Exists
placementBindingDefaults:
  name: base-monitor-binding

policies:
  - name: monitor-cluster-operators
    description: monitor cluster operators
    complianceType: mustnothave
    manifests:
      - path: monitor/cluster-operator-status.yaml

  - name: monitor-nodes
    description: monitor nodes with memory, disk or pid pressure, or not ready
    complianceType: mustnothave
    manifests:
      - path: monitor/node-status.yaml

  - name: monitor-machine-config-pool
    description: monitor machine config pool with degraded or unavailable machines
    manifests:
      - path: monitor/machine-config-pool-status.yaml

  - name: monitor-operator-hub
    description: monitor operator hub and catalog sources
    manifests:
      - path: monitor/operator-hub/catalog-source-status.yaml
      - path: monitor/operator-hub/operator-hub-status.yaml

  - name: monitor-control-plane-node-schedulable
    description: monitor control plane nodes that are schedulable
    complianceType: mustnothave
    manifests:
      - path: monitor/control-plane-node-schedulable.yaml

  - name: monitor-etcd-encryption
    description: verify that etcd encryption has completed
    complianceType: musthave
    manifests:
      - path: monitor/etcd-encryption-status.yaml

  - name: monitor-cluster-version
    description: monitor cluster version
    complianceType: musthave
    manifests:
      - path: monitor/cluster-version-status.yaml

  - name: monitor-failed-cluster-service-version
    description: monitor failed cluster service version
    complianceType: mustnothave
    severity: low
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      exclude:
        - etcd-backup
        - disable-insights
        - kube-*
        - openshift
        - openshift-apiserver*
        - openshift-authentication*
        - openshift-catalogd
        - openshift-cloud-*
        - openshift-cluster-csi-drivers
        - openshift-cluster-machine-approver
        - openshift-cluster-node-tuning-operator
        - openshift-cluster-olm-operator
        - openshift-cluster-samples-operator
        - openshift-cluster-storage-operator
        - openshift-cluster-version
        - openshift-config*
        - openshift-console*
        - openshift-controller-manager*
        - openshift-dns*
        - openshift-etcd*
        - openshift-host-network
        - openshift-image-registry
        - openshift-infra
        - openshift-ingress*
        - openshift-insights
        - openshift-kni-infra
        - openshift-kube-*
        - openshift-machine-*
        - openshift-monitoring
        - openshift-multus
        - openshift-network-*
        - openshift-node
        - openshift-oauth-apiserver
        - openshift-openstack-infra
        - openshift-ovirt-infra
        - openshift-ovn-kubernetes
        - openshift-route-controller-manager
        - openshift-service-ca*
        - openshift-storage
        - openshift-user-workload-monitoring
        - rhacm-policies
    manifests:
      - path: monitor/cluster-service-version-status.yaml

  - name: monitor-cluster-log-forwarder
    description: monitor cluster log forwarder status is ready
    complianceType: musthave
    manifests:
      - path: monitor/cluster-log-forwarder.yaml

  - name: monitor-rhacs-secured-clusters
    description: monitor rhacs securedCluster deployments
    complianceType: musthave
    manifests:
      - path: monitor/rhacs-secured-cluster-status.yaml

  - name: monitor-tekton-config-status
    description: monitor openshift pipelines components status are ready
    complianceType: musthave
    manifests:
      - path: monitor/tekton-config-status.yaml

  - name: monitor-role-with-wildcard-permissions
    description: detect namespaced Role with wildcard permissions
    complianceType: mustnothave
    namespaceSelector:
      include:
        - "*"
    manifests:
      - path: monitor/role-with-wildcard-permissions.yaml

  - name: monitor-privileges-scc-binding
    description: monitor namespaced role granting access to privileged scc
    complianceType: mustnothave
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      include:
        - "*"
      exclude:
        - etcd-backup          # etcd backup cronjob run as privileged container
        - openshift-frr-k8s    # frr (free range routing) instances deployed by metal lb
    manifests:
      - path: monitor/privileged-scc-role-binding.yaml

  - name: monitor-terminating-namespaces
    description: monitor namespaces stuck in the Terminating state
    complianceType: mustnothave
    manifests:
      - path: monitor/namespace-status.yaml

  - name: monitor-install-plans
    description: monitor install plans pending approval
    complianceType: mustnothave
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      include:
        - "*"
    manifests:
      - path: monitor/install-plan-status.yaml

  - name: monitor-pod-disruption-budget
    description: monitor pod disruption budget with insufficient pods
    complianceType: mustnothave
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      include:
        - "*"
    manifests:
      - path: monitor/pod-disruption-budget-status.yaml

  - name: monitor-pod-using-default-service-account
    description: monitor pod using the default service account.
    complianceType: mustnothave
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      exclude:
        - "kube-*"
        - "openshift*"
        - "open-cluster-management*"
        - "knative-*"
        - keycloak
        - assisted-installer
      include:
        - "*"
    manifests:
      - path: monitor/pod-using-default-service-account.yaml

  - name: monitor-pod-with-more-than-200-restarts
    description: monitor pods with more than 200 restarts
    manifests:
      - path: monitor/pod-restarts.yaml

  - name: monitor-container-oom-killed
    description: monitor container oom-killed
    complianceType: mustnothave
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      include:
        - "*"
    manifests:
      - path: monitor/container-oom-killed.yaml

  - name: monitor-container-crash-loop-backoff
    description: monitor pod/container CrashLoopBackOff
    complianceType: mustnothave
    severity: low
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      include:
        - "*"
    manifests:
      - path: monitor/container-crash-loop-backoff.yaml

  - name: monitor-container-image-pull-backoff
    description: monitor pod/container ImagePullBackOff
    complianceType: mustnothave
    severity: low
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      include:
        - "*"
    manifests:
      - path: monitor/container-image-pull-backoff.yaml

  - name: monitor-persistent-volume
    description: monitor persistent volume in failed/released state
    complianceType: mustnothave
    manifests:
      - path: monitor/persistent-volume-status.yaml

  - name: monitor-persistent-volume-claim
    description: monitor persistent volume claims that are not in Bound state
    complianceType: mustnothave
    severity: low
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      include:
        - "*"
    manifests:
      - path: monitor/persistent-volume-claim-status.yaml

  - name: monitor-default-storage-class
    description: monitor to ensure only one default storage class
    manifests:
      - path: monitor/default-storage-class.yaml

  - name: monitor-operator-group
    description: monitor namespaces that have more than one operatorGroup
    manifests:
      - path: monitor/operator-group-status.yaml

  - name: monitor-failed-cronjob
    description: monitor cronJobs that failed their last scheduled run
    manifests:
      - path: monitor/failed-cronjob-status.yaml

  - name: monitor-openshift-route
    description: monitor routes that are not admitted
    complianceType: mustnothave
    namespaceSelector:          # required when the templates/manifests does not have metadata.namespace
      include:
        - "*"
    manifests:
      - path: monitor/route-status.yaml

  - name: monitor-openshift-serverless
    description: monitor openshift-serverless components
    complianceType: musthave
    policySets:                 # override policyDefaults.policySets
      - base-monitor-openshift-serverless
    manifests:
      - path: monitor/openshift-serverless/knative-serving.yaml
      - path: monitor/openshift-serverless/knative-eventing.yaml

  - name: monitor-metallb-status
    description: monitor metallb status
    complianceType: musthave
    policySets:                 # override policyDefaults.policySets
      - base-monitor-metallb
    manifests:
      - path: monitor/metallb/metallb-status.yaml
      - path: monitor/metallb/frr-node-state.yaml

  - name: monitor-metallb-nearly-depleted-ip-address-pool
    description: monitor metallb ip address pools that are 80% or more assigned
    policySets:                 # override policyDefaults.policySets
      - base-monitor-metallb
    manifests:
      - path: monitor/metallb/ip-address-pool.yaml
...
