---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: pg-monitoring
policyDefaults:
  namespace: rhacm-policies
  policyAnnotations:
    generated-by: policy-generator
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  standards:
    - NIST SP 800-53
  categories:
    - CA Assessment Authorization and Monitoring
  controls:
    - CA-07 Continuous Monitoring
  remediationAction: inform
  severity: medium
  policySets:
    - monitor-all-clusters
policySets:
  - name: monitor-all-clusters
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
          - key: managed-hub
            operator: DoesNotExist
  - name: monitor-local-cluster
    placement:
      labelSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - local-cluster
  - name: monitor-managed-hubs
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
          - key: managed-hub
            operator: Exists
placementBindingDefaults:
  name: binding-monitor

policies:
  - name: monitor-cluster-operators
    complianceType: mustnothave
    manifests:
      - path: monitor/cluster-operator-status.yaml

  - name: monitor-nodes
    complianceType: mustnothave
    manifests:
      - path: monitor/node-status.yaml

  - name: monitor-managed-clusters
    complianceType: musthave
    policySets:           # override policyDefaults.policySets
      - monitor-local-cluster
      - monitor-managed-hubs
    manifests:
      - path: monitor/managed-cluster-status.yaml

  - name: monitor-managed-hubs-no-local-cluster
    complianceType: mustnothave
    policySets:           # override policyDefaults.policySets
      - monitor-managed-hubs
    manifests:
      - path: monitor/managed-hubs-local-cluster.yaml

  - name: monitor-rhacs-central
    complianceType: musthave
    policySets:           # override policyDefaults.policySets
      - monitor-local-cluster
      - monitor-managed-hubs
    manifests:
      - path: monitor/rhacs-central-status.yaml

  - name: monitor-rhacs-secured-clusters
    complianceType: musthave
    namespaceSelector:
      include:
        - "stackrox"
    manifests:
      - path: monitor/rhacs-secured-cluster-status.yaml

  - name: monitor-wildcard-permissions-role
    complianceType: mustnothave
    namespaceSelector:
      include:
        - "*"
    manifests:
      - path: monitor/wildcard-permissions-role.yaml

  - name: monitor-privileges-scc-binding
    complianceType: mustnothave
    namespaceSelector:
      include:
        - "*"
    manifests:
      - path: monitor/privileged-scc-role-binding.yaml

  - name: monitor-terminating-namespaces
    complianceType: mustnothave
    manifests:
      - path: monitor/namespace-status.yaml

  - name: monitor-install-plans
    complianceType: mustnothave
    namespaceSelector:
      include:
        - "*"
    manifests:
      - path: monitor/install-plan-status.yaml

  - name: monitor-container-oom-killed
    complianceType: mustnothave
    namespaceSelector:
      include:
        - "*"
    manifests:
      - path: monitor/container-oom-killed.yaml

  - name: monitor-container-crash-loop-backoff
    complianceType: mustnothave
    severity: low
    namespaceSelector:
      include:
        - "*"
    manifests:
      - path: monitor/container-crash-loop-backoff.yaml

  - name: monitor-container-image-pull-backoff
    complianceType: mustnothave
    severity: low
    namespaceSelector:
      include:
        - "*"
    manifests:
      - path: monitor/container-image-pull-backoff.yaml
...
