---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: pg-config
policyDefaults:
  namespace: rhacm-policies
  policyAnnotations:
    generated-by: policy-generator
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  standards:
    - NIST SP 800-53
  categories:
    - CM Configuration Management
  controls:
    - CM-02 Baseline Configuration
  remediationAction: enforce
  policySets:
    - ps-config-all-clusters
  severity: medium
policySets:
  - name: ps-config-all-clusters
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
  - name: ps-config-managed-hubs
    placement:
      labelSelector:
        matchExpressions:
          - key: managed-hub
            operator: Exists
  - name: ps-config-no-local-cluster-no-managed-hub
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
          - key: name
            operator: NotIn
            values:
              - local-cluster
          - key: managed-hub
            operator: DoesNotExist

placementBindingDefaults:
  name: binding-config

policies:
  - name: config-remove-kubeadmin
    complianceType: mustnothave
    categories:
      - AC Access Control
    controls:
      - AC-02 Account Management
    manifests:
      - path: config/kubeadmin-secret.yaml

  - name: config-argocd-repo-secrets
    policySets:         # override policyDefaults.policySets
      - ps-config-managed-hubs
    manifests:
      - path: config/openshift-gitops/repo-secret.yaml

  - name: config-rhacs-secured-cluster
    complianceType: musthave
    policySets:         # override policyDefaults.policySets
      - ps-config-no-local-cluster-no-managed-hub
    manifests:
      - path: config/rhacs/secured-cluster.yaml
      - path: config/rhacs/secret.yaml
...
