---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: base-config-policy
policyDefaults:
  namespace: rhacm-policies
  policyAnnotations:
    generated-by: policy-generator
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  standards:
    - NIST SP 800-53
  categories:
    - CM Configuration Management
  controls:
    - CM-02 Baseline Configuration
  remediationAction: enforce
  policySets:
    - base-config-all-clusters
  severity: medium
policySets:
  - name: base-config-all-clusters
    description: base config policies for all clusters
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
  - name: base-config-no-local-cluster-no-managed-hub
    description: base config policies for all clusters, except local-cluster and managed-hub
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
          - key: name
            operator: NotIn
            values:
              - local-cluster
          - key: managed-hub
            operator: DoesNotExist
  - name: base-config-metallb
    description: base config policies for all clusters with metallb label
    placement:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
              - OpenShift
          - key: metallb
            operator: DoesNotExist

placementBindingDefaults:
  name: base-config-binding

policies:
  - name: config-remove-kubeadmin
    description: remove kube-system/kubeadmin secret
    complianceType: mustnothave
    categories:
      - AC Access Control
    controls:
      - AC-02 Account Management
    manifests:
      - path: config/kubeadmin-secret.yaml

  - name: config-rhacs-secured-cluster
    description: deploy rhacs operator, securedCluster and cluster registration secret
    complianceType: musthave
    policySets:         # override policyDefaults.policySets
      - base-config-no-local-cluster-no-managed-hub
    manifests:
      - path: config/rhacs/secured-cluster.yaml
      - path: config/rhacs/secret.yaml

  - name: config-openshift-logging-http-secret
    description: copy openshift logging http endpoint authentication secrets to all clusters, except hub clusters
    complianceType: musthave
    policySets:         # override policyDefaults.policySets
      - base-config-no-local-cluster-no-managed-hub
    manifests:
      - path: config/openshift-logging/secret.yaml

  - name: config-metallb-bgp-password-secret
    description: copy metallb bgp password secret from managed hub to managed clusters
    policySets:         # override policyDefaults.policySets
      - base-config-metallb
    manifests:
      - path: config/metallb-bgp-password-secret.yaml
...
