---
apiVersion: search.open-cluster-management.io/v1alpha1
kind: Search
metadata:
  name: search-v2-operator
  namespace: open-cluster-management
  annotations:
    global-search-preview: "true"
    argocd.argoproj.io/sync-wave: "105"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
...
