---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.snapshot.name }}
  namespace: {{ .Values.namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.pvc.snapshot.size }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{ .Values.pvc.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.staticResources.name }}
  namespace: {{ .Values.namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.pvc.staticResources.size }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{ .Values.pvc.storageClass }}
...
