---
deploymentType: all             # operator, multicluster-hub, all
rhacmNamespace: open-cluster-management
operatorChannel: release-2.17
availabilityConfig: High        # Basic or High
disableHubSelfManagement: false
...
