{{- if has .Values.deploymentType (list "mch" "operator+mch" "all") }}
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: {{ .Values.rhacmNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  localClusterName: local-cluster
  availabilityConfig: {{ .Values.availabilityConfig }}
  {{- if .Values.disableHubSelfManagement }}
  disableHubSelfManagement: {{ .Values.disableHubSelfManagement }}
  {{- end }}
...
{{- end }}
