---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
spec:
  centralEndpoint: '{{hub fromConfigMap "rhacm-policies" "rhacs-central-endpoint" "centralEndpoint" hub}}'
...
