{{- if has .Values.deploymentType (list "central" "all") }}
---
kind: SecurityPolicy
apiVersion: config.stackrox.io/v1alpha1
metadata:
  name: cluster-wide-rbac
  namespace: {{ .Values.namespace.central }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    # argocd dry-run may fail because the crd is not registered yet
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  policyName: cluster wide RBAC
  description: cluster wide RBAC
  rationale: Granting cluster wide access to resources is a security risk.
  remediation: Do not grant cluster wide access to resources to service account; use roleBinding (oc adm policy add-role-to-user) instead of clusterRoleBinding (oc adm policy add-cluster-role-to-user) .
  disabled: false
  categories:
    - DevOps Best Practices
    - Security Best Practices
    - Privileges
  lifecycleStages:
    - DEPLOY
  eventSource: NOT_APPLICABLE
  exclusions:
  {{- $exclusions := list "openshift" "rhacm" "rhacs" "etcd-backup" "openshift-serverless" "metallb" "keycloak" -}}
{{ include "rhacs.setExclusions" (dict "root" $ "exclusions" $exclusions) | indent 4 }}
  scope: []
  severity: MEDIUM_SEVERITY
  enforcementActions:
    - SCALE_TO_ZERO_ENFORCEMENT
    - UNSATISFIABLE_NODE_CONSTRAINT_ENFORCEMENT
  notifiers: []
  policySections:
    - sectionName: pod has cluster wide permission
      policyGroups:
        - fieldName: Minimum RBAC Permissions
          booleanOperator: OR
          negate: false
          values:
            - value: ELEVATED_CLUSTER_WIDE
...
{{- end }}
