{{- if has .Values.deploymentType (list "central" "all") }}
---
kind: SecurityPolicy
apiVersion: config.stackrox.io/v1alpha1
metadata:
  name: mounting-hostpath
  namespace: {{ .Values.namespace.central }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    # argocd dry-run may fail because the crd is not registered yet
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  policyName: mounting hostPath
  description: mounting hostPath
  rationale: Mounting of hostPath implies container can access files on the host. This expands the attack surface of the container and gives an intruder an opportunity to break containment if the host is not properly secured.
  remediation: Ensure that deployment do not mount hostPath, or exclude this deployment if hostPath mount is required.
  disabled: false
  categories:
    - DevOps Best Practices
    - Security Best Practices
    - Privileges
  lifecycleStages:
    - DEPLOY
  eventSource: NOT_APPLICABLE
  exclusions:
  {{- $exclusions := list "openshift" "rhacm" "rhacs" -}}
{{ include "rhacs.setExclusions" (dict "root" $ "exclusions" $exclusions) | indent 4 }}
  scope: []
  severity: MEDIUM_SEVERITY
  enforcementActions: []
  notifiers: []
  policySections:
  - sectionName: volume type hostPath
    policyGroups:
    - fieldName: Volume Type
      booleanOperator: OR
      negate: false
      values:
      - value: HostPath
...
{{- end }}
