---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 00-managed-hub-app-of-apps           # prefix Application name with 00 for sorting purpose
  namespace: openshift-gitops
  labels:
    applications: managed-hub-app-of-apps
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: managed-hub
              operator: Exists
            - key: env
              operator: In
              value:
                - dev
  template:
    metadata:
      name: "00-{{ name }}-app-of-apps"
      labels:
        applications: managed-hub-app-of-apps
    spec:
      project: iac-gitops
      source:
        repoURL: https://github.com/bkkhoo/argocd.git
        path: root-app/managed-hub/dev
        targetRevision: main
      destination:
        server: "{{ server }}"
      syncPolicy:
        automated:
          prune: false       # the config here modify pre-existing resources that are part of openshift
          selfHeal: true     # do not delete the resources when they are no longer defined in git
        syncOptions:
          - CreateNamespace=true
...
