{{- if eq .Values.deploymentType "central" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.central }}
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
spec: {}
...
{{- end }}
