{{- if eq .Values.deploymentType "central" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: declarative-auth-provider
  namespace: {{ .Values.namespace.central }}
stringData:
  openshift-auth.yaml: |
    name: "OpenShift Auth"
    minimumRole: {{ .Values.minimumAccessRole }}
    openshift:
      enable: true
...
{{- end }}
