---
apiVersion: v2
appVersion: 1.21      # the version depends on openshift catalog source, need not necessary match what is specified here
name: openshift-gitops
description: Red Hat OpenShift GitOps
type: application
version: 1.0
...
