---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: auto-import-secret
  namespace: {{ required "the value clusterName is required" .Values.clusterName }}
stringData:
  token: {{ required "the value clusterAuthToken is required" .Values.clusterAuthToken }}
  server: {{ required "the value clusterURL is required" .Values.clusterURL }}
...
