---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhacs-operator-controller-manager
  namespace: rhacs-operator
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-db
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-db
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-v4-db
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-v4-indexer
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-v4-matcher
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
# also include securedCluster components
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-control
  namespace: stackrox
status:
  conditions:
    - type: Available
      status: "True"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
  namespace: stackrox
status:
  numberMisscheduled: 0
...
