{{- if has .Values.deploymentType (list "operator" "all") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-post-sync-hook
  namespace: {{ .Values.namespace.operator }}
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
data:
  enable-gitops-console-plugin.sh: |
{{ .Files.Get "files/enable-gitops-console-plugin.sh" | indent 4 }}
...
{{- end }}
