---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-sync-hook
  namespace: {{ .Values.namespace.operator }}
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
data:
  add-plugin-to-console-operator.sh: |
{{ .Files.Get "files/add-plugin-to-console-operator.sh" | indent 4 }}
...
