{{- if has .Values.deploymentType (list "operator" "all") }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: enable-gitops-console-plugin
  namespace: {{ .Values.namespace.operator }}
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: create-crs
          image: registry.redhat.io/openshift4/ose-tools-rhel9:v4.20
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - /scripts/enable-gitops-console-plugin.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: gitops-post-sync-hook
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: gitops-post-sync-hook
      terminationGracePeriodSeconds: 30
...
{{- end }}
