{{- if has .Values.deploymentType (list "operator" "all") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-post-sync-hook
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-gitops-post-sync-hook
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-post-sync-hook
subjects:
  - kind: ServiceAccount
    name: gitops-post-sync-hook
    namespace: {{ .Values.namespace.operator }}
...
{{- end }}
