---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-sync-hook
  namespace: {{ .Values.namespace.operator }}
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
...
