---
projectTemplateOverride: "false"
resourceQuota:
  requests:
    cpu: "5"
    memory: 5Gi
  limits:
    cpu: "5"
    memory: 5Gi
limitRange:
  default:
    cpu: 500m
    memory: 512Mi
  defaultRequest:
    cpu: 250m
    memory: 256Mi
  max:
    cpu: "1"
    memory: 1Gi
  min:
    cpu: 125m
    memory: 128Mi
...
