---
apiVersion: v2
name: rhacs
description: Red Hat Advanced Cluster Security for Kubernetes
type: application
version: 1.0
appVersion: 4.10    # The OpenShift GitOps version depends on catalog source, need not necessary match what is specified here
...
