---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-serverless
  namespace: openshift-gitops
  labels:
    applications: openshift-serverless
spec:
  goTemplate: true                     # enable go templating for spec.template field
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters:                        # on global-hub, deploy to all clusters except those with managed-hub label
        selector:                      # on managed-hubs, no cluster should have the managed-hub label
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
            - key: managed-hub
              operator: DoesNotExist
            - key: openshift-serverless
              operator: Exists
  template:
    metadata:
      name: "{{ .name }}-openshift-serverless"
      labels:
        applications: openshift-serverless
    spec:
      project: gitops
      source:
        repoURL: https://github.com/bkkhoo/argocd.git
        targetRevision: main
        path: helm-charts/openshift-serverless
        # if the cluster has openshift-service-mesh label, enabled KnativeServing and KnativeEventing istio integration config
        # the app will not converge if istio integration is configured without service mesh installed
        helm:
          valuesObject:
            serviceMeshIntegration: '{{ if index .metadata.labels "openshift-service-mesh" }}true{{ else }}false{{ end }}'
      destination:
        server: "{{ .server }}"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      info:
        - name: env
          value: any
        - name: type
          value: applicationSet
        - name: target
          value: clusters with openshift-serverless but without managed-hub labels
...
