---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-serverless
  namespace: openshift-gitops
  labels:
    applications: openshift-serverless
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters:                        # on global-hub, deploy to all clusters except those with managed-hub label
        selector:                      # on managed-hubs, no cluster should have the managed-hub label
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
            - key: managed-hub
              operator: DoesNotExist
            - key: openshift-serverless
              operator: Exists
  template:
    metadata:
      name: "{{ name }}-openshift-serverless"
      labels:
        applications: openshift-serverless
    spec:
      project: iac-gitops
      source:
        repoURL: https://github.com/bkkhoo/argocd.git
        targetRevision: main
        path: helm-charts/openshift-serverless
        helm:
          valuesObject:
            serviceMeshIntegration: false
      destination:
        server: "{{ server }}"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
...
