---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-app-uat
resources:
  - ../../base
helmGlobals:
  chartHome: ../../../../helm-charts
helmCharts:
  - name: test-chart-1
    valuesFile: values-1.yaml
  - name: test-chart-2
    valuesFile: values-2.yaml
...
