---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/rhacm-policies/base
  - ../../../apps/cluster-config/base

  - ../../../apps/openshift-web-terminal/base
  # - ../../../apps/openshift-compliance/base
  # - ../../../apps/rhacs-central/uat
  # - ../../../apps/rhacs-secured-cluster/uat
  # - ../../../apps/test1/uat
...
