---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # the following are for managed hubs
  - ../../../apps/01-managed-hub-bootstrap/dev
  - ../../../apps/01-managed-hub-bootstrap/uat
  - ../../../apps/01-managed-hub-bootstrap/prod

  # apps that target in-cluster only
  - ../../../apps/rhacm-policies/base
  - ../../../apps/rhacs-central/prod

  # apps that target all clusters (generators[0].clusters: {})
  # reuse these apps for deployment to global-hub cluster, patch to make them target only in-cluster
  - ../../../apps/cluster-config/base
  - ../../../apps/openshift-web-terminal/base
  - ../../../apps/openshift-compliance/base

# patch to:
# - add '01' prefix to the apps for sorting purpose, and
# - change generator to list with in-cluster only
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: cluster-config
    patch: |
      - op: replace
        path: /spec/template/metadata/name
        value: "01-cluster-config"
      - op: replace
        path: /spec/generators/0
        value:
          list:
            elements:
              - name: in-cluster
                server: https://kubernetes.default.svc
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: openshift-web-terminal
    patch: |
      - op: replace
        path: /spec/template/metadata/name
        value: "01-openshift-web-terminal"
      - op: replace
        path: /spec/generators/0
        value:
          list:
            elements:
              - name: in-cluster
                server: https://kubernetes.default.svc
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: openshift-compliance
    patch: |
      - op: replace
        path: /spec/template/metadata/name
        value: "01-openshift-compliance"
      - op: replace
        path: /spec/generators/0
        value:
          list:
            elements:
              - name: in-cluster
                server: https://kubernetes.default.svc
...
