---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # the following are for managed hubs
  - ../../../apps/02-managed-hub-bootstrap/dev
  - ../../../apps/02-managed-hub-bootstrap/uat
  - ../../../apps/02-managed-hub-bootstrap/prod

  # for the global hub itself
  - ../../../apps/rhacm-policies/base
  - ../../../apps/cluster-config/base            # this app set deploys to all clusters, patch to deploy to locally

  # other apps to deploy to global-hub
  - ../../../apps/openshift-web-terminal/base    # this app set deploys to all clusters, patch to deploy to locally
  - ../../../apps/openshift-compliance/base      # this app set deploys to all clusters, patch to deploy to locally
  # - ../../../apps/rhacs-central/prod

patches:
  # remove the config-rhacs-secured-cluster rhacm policy
  - patch: |-
      $patch: delete
      group: policy.open-cluster-management.io
      apiVersion: v1
      kind: Policy
      metadata:
        name: config-rhacs-secured-cluster
  # apps/cluster-config is set to deploy to all clusters, it is meant for managed-hubs
  # patch the app so that it targets only in-cluster of global-hub
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: cluster-config
    patch: |
      - op: replace
        path: /spec/template/metadata/name
        value: "01-cluster-config"
      - op: replace
        path: /spec/generators/0
        value:
          list:
            elements:
              - name: in-cluster
                server: https://kubernetes.default.svc
  # apps/openshift-web-terminal is set to deploy to all clusters, it is meant for managed-hubs
  # patch the app so that it targets only in-cluster of global-hub
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: openshift-web-terminal
    patch: |
      - op: replace
        path: /spec/template/metadata/name
        value: "01-openshift-web-terminal"
      - op: replace
        path: /spec/generators/0
        value:
          list:
            elements:
              - name: in-cluster
                server: https://kubernetes.default.svc
  # apps/openshift-compliance is set to deploy to all clusters, it is meant for managed-hubs
  # patch the app so that it targets only in-cluster of global-hub
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: openshift-compliance
    patch: |
      - op: replace
        path: /spec/template/metadata/name
        value: "01-openshift-compliance"
      - op: replace
        path: /spec/generators/0
        value:
          list:
            elements:
              - name: in-cluster
                server: https://kubernetes.default.svc
...
