---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
status:
  conditions:
    - status: Unknown
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
status:
  conditions:
    - status: "False"
...
