---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: multicluster-global-hub-agent
    namespace: multicluster-global-hub-agent
status:
  conditions:
    - status: "True"
      type: Available
...
