---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights-sync-hook
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: insights-sync-hook
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - pull-secret
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: insights-sync-hook
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: insights-sync-hook
subjects:
  - kind: ServiceAccount
    name: insights-sync-hook
    namespace: {{ .Values.namespace }}
...
