---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-global-hub-app-of-apps            # prefix Application name with 00 for sorting purpose
  namespace: openshift-gitops
  labels:
    applications: global-hub-app-of-apps
spec:
  project: iac-gitops
  source:
    repoURL: https://github.com/bkkhoo/argocd.git
    path: root-app/global-hub/base
    targetRevision: main
  destination:
    name: in-cluster
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
