:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= Overview

The following outlines the Cribl.Cloud configuration:

- Create Cribl HTTP and Raw HTTP Sources to accept logs forwarded by the OpenShift `ClusterLogForwarder`:
  ** Configure OpenShift `ClusterLogForwarder` output to use `ndjson` format when forwarding to Cribl HTTP Source:
     *** `ClusterLogForwarder` aggregates (with `ndjson`, each event json objects are separated by newline) and compresses (gzip) logs into a single giant batch by default rather than forwarding individually.
     *** Cribl HTTP Source is protocol-ware and explicitly has no Event Breaker support; its can accept multiple newline-delimited JSON event objects, treating each NDJSON line as an event.
  ** Configure OpenShift `ClusterLogForwarder` output to use `json` format when forwarding to Cribl Raw HTTP Source:
     *** `ClusterLogForwarder` aggregates and compresses (gzip) logs into a single giant batch (e.g., `[{"@timestamp":...},{"@timestamp":...}...]`) by default rather than forwarding individually.
     *** Cribl Raw HTTP Source treats the batch as raw input and assigns everything to `_raw` field.
     *** Configure a Cribl Event Breaker to break the aggregated logs in the `_raw` field back into individual log events inside Cribl.
- Route logs to data destinations (OpenShift LokiStack and Cribl Data Lake) based on the `log_type` field.
- Process events/logs with Cribl Pipelines to:
  ** Add labels for Loki indexing.
  ** Remove fields (such as namespace, pod, and container IDs).
  ** Drop GET, LIST, and WATCH audit events, unless they are for `Secrets` resource.
  ** Drop successful actions (response code 200, 201) on `SubjectAccessReviews`, `TokenReviews` and `Leases` audit events.
  ** Apply a 10% sample rate to INFO/DEBUG/TRACE application and infrastructure logs.

== Cribl.Cloud Configuration

. Optionally, get CA certificate for Cribl.Cloud:
+
[source,bash]
----
curl https://i.pki.goog/r1.pem > cribl-cloud-ca.crt
curl https://i.pki.goog/wr1.pem >> cribl-cloud-ca.crt
----
+
[NOTE]
====
Generally, users do not need to download CA certificates for Cribl.Cloud manually because Cribl.Cloud uses Google Trust Services (GTS) as its Certificate Authority.

To manually download the required certificates:

- Visit the link:https://pki.goog/repository/[Google Trust Services Root Repository].
- Download and store the following CA certificates:
  ** The GTS Root R1 certificate in PEM format.
  ** The WR1 intermediates/subordinate certificate in PEM format.
====

. One time tasks:
  .. Create API Credential on Cribl Cloud UI:
     * Login to link:https://manage.cribl.cloud/[Cribl Cloud].
     * Click **Products** on the top left corner of the UI.
     * Click **Cribl** from the side menu.
     * Select **API Credential** from the side menu.
     * Copy the **Client ID** and **Client Secret** and store as Ansible vault encrypted secrets.
  .. Get Organization ID:
     * Click **Products** on the top left corner of the UI.
     * Click **Organization** from the side menu.
     * Copy the **Organization ID** and store as Ansible vault encrypted secrets.
  .. Get Workspace:
     * Click **Products** on the top left corner of the UI.
     * Click **Workspace** from the side menu.
     * Copy the **Workspace name** and store as Ansible vault encrypted secrets.
  .. Get Worker Group:
     * Click **Products** on the top left corner of the UI.
     * Click **Worker Groups** from the side menu.
     * Pick a worker group, copy the **Worker Group name** and store as Ansible vault encrypted secrets.

. Create/Update secrets:

- update link:./ansible/vars/cribl-secrets-vault-encrypted.yaml[cribl-secrets-vault-encrypted.yaml] (note: the file is encrypted); see link:./ansible/vars/_example-cribl-secrets.yaml[_example-cribl-secrets.yaml] for the format of the file.
- update link:./ansible/vars/openshift-logging-token-vault-encrypted.yaml[openshift-logging-token-vault-encrypted.yaml] (note: the file is encrypted); see link:./ansible/vars/_example-openshift-logging-token.yaml[_example-openshift-logging-token.yaml] for the format of the file.

. Run Ansible playbook to configure Cribl.Cloud:
+
[source,bash]
----
ansible-playbook -i localhost, ansible/configure-cribl.yaml
----

== Remove the Cribl.Cloud Configuration

[source,bash]
----
ansible-playbook -i localhost, ansible/unconfigure-cribl.yaml
----
