:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= Cribl.Cloud Configuration

. Optionally, get CA certificate for Cribl.Cloud:
+
[source,bash]
----
curl https://i.pki.goog/r1.pem > cribl-stream-ca.crt
curl https://i.pki.goog/wr1.pem >> cribl-stream-ca.crt
----
+
[NOTE]
====
Generally users do not need to download CA certificate for Cribl.Cloud manually because Cribl.Cloud uses Google Trust Services (GTS) as its Certificate Authority.

To manually download the required certificates:

- visit link:https://pki.goog/repository/[Google Trust Services Root Repository].
- download the GTS Root R1 certificate in PEM format.
- download the WR1 intermediate certificate in PEM format.
====

. One time task, create API Credential on Cribl Cloud UI:

* Login to link:https://manage.cribl.cloud/[Cribl Cloud].
* Click **Products** on the top left corner of the UI.
* Click **Cribl** from the side menu.
* Select **API Credential** from the side menu.
* Click **Add Credential**.
* Store **Client ID** and **Client Secret** in the files respectively:
  ** `secrets/client-id`
  ** `secrets/client-secret`

. Get Organization ID:
+
* Click **Products** on the top left corner of the UI.
* Click **Organization** from the side menu.
* Set environment variable:
+
[source,bash]
----
export ORG_ID="stoic-gauss-qcj0f23"
export WORKSPACE="main"
export WORKER_GROUP="default"
----

. Get API token:
+
[source,bash]
----
export CRIBL_API_TOKEN=$(
curl --request POST 'https://login.cribl.cloud/oauth/token' \
  --header 'Content-Type: application/json' \
  --data "
{
  \"grant_type\": \"client_credentials\",
  \"client_id\": \"$(cat secrets/client-id)\",
  \"client_secret\": \"$(cat secrets/client-secret)\",
  \"audience\": \"https://api.cribl.cloud\"
}" | jq -r .access_token)
----
+
[NOTE]
====
The token is valid for 1 day only.
====

. Create Cribl Stream secret:
+
[source,bash]
----
curl --request POST https://${WORKSPACE}-${ORG_ID}.cribl.cloud/api/v1/m/${WORKER_GROUP}/system/secrets \
  --header "Authorization: Bearer ${CRIBL_API_TOKEN}" \
  --header "Content-Type: application/json" \
  --data "{
    \"id\": \"openshift-loki-log-collector-token-111\",
    \"secretType\": \"text\",
    \"value\": \"$(oc -n openshift-logging create token external-logs-writer --duration=8760h)\",
    \"description\": \"oc -n openshift-logging create token external-logs-writer --duration=8760h\"
  }"
----
+
[NOTE]
====
- OpenShift LokiStack uses bearer token to authenticate/authorize logs ingestion. The ServiceAccount token must be granted the `logging-collector-logs-writer` ClusterRole.
- The link:../../helm-charts/loki-stack/templates/rbac.yaml[Helm chart template] create the ServiceAccount and ClusterRoleBinding to grant the required privileges.
====

. Create Cribl Stream pipelines:
+
[source,bash]
----
for p in drop-90-percent application infrastructure audit; do
  curl --request POST https://${WORKSPACE}-${ORG_ID}.cribl.cloud/api/v1/m/${WORKER_GROUP}/pipelines \
    --header "Authorization: Bearer ${CRIBL_API_TOKEN}" \
    --header "Content-Type: application/json" \
    --data @pipeline/${p}.json
  echo ""
done
----

. Create Cribl Stream HTTP data destinations:
+
[source,bash]
----
for d in output-router application infrastructure audit; do
  curl --request POST https://${WORKSPACE}-${ORG_ID}.cribl.cloud/api/v1/m/${WORKER_GROUP}/system/outputs \
    --header "Authorization: Bearer ${CRIBL_API_TOKEN}" \
    --header "Content-Type: application/json" \
    --data @destination/${d}.json
  echo ""
done
----

. Create Cribl Stream HTTP data source:
+
[source,bash]
----
curl --request POST https://${WORKSPACE}-${ORG_ID}.cribl.cloud/api/v1/m/${WORKER_GROUP}/system/inputs \
  --header "Authorization: Bearer ${CRIBL_API_TOKEN}" \
  --header "Content-Type: application/json" \
  --data @source/http.json
----

. Commit and Deploy:
+
[source,bash]
----
COMMIT_ID=$(
curl --request POST https://${WORKSPACE}-${ORG_ID}.cribl.cloud/api/v1/version/commit \
  --header "Authorization: Bearer ${CRIBL_API_TOKEN}" \
  --header "Content-Type: application/json" \
  --data '{ "message": "automation@cribl:commit" }' | jq -r .items[0].commit)

curl --request PATCH https://${WORKSPACE}-${ORG_ID}.cribl.cloud/api/v1/products/stream/groups/${WORKER_GROUP}/deploy \
  --header "Authorization: Bearer ${CRIBL_API_TOKEN}" \
  --header "Content-Type: application/json" \
  --data "{\"version\": \"${COMMIT_ID}\"}"
----
