# this template copy list of secrets (with rhacm-policies/sync-hub-secret=yes):
#  -from global-hub rhacm-policies namespace
# - to managed-hub
# only data pertinent to the managed-hub env (dev/uat/prod) is copied to the managed-hub
---
object-templates-raw: |
  {{- $env := (lookup "cluster.open-cluster-management.io/v1alpha1" "ClusterClaim" "" "env").spec.value | default "prod" }}
  {{hub range $secret := (lookup "v1" "Secret" "rhacm-policies" "" "rhacm-policies/sync-hub-secret=yes").items hub}}
    {{hub- if eq (index $secret.metadata.annotations "rhacm-policies/structure") "list" hub}}
      {{- if eq $env "dev" }}
        {{hub- $data := $secret.data.dev hub}}
      {{- end }}
      {{- if eq $env "uat" }}
        {{hub- $data := $secret.data.uat hub}}
      {{- end }}
      {{- if eq $env "prod" }}
        {{hub- $data := $secret.data.prod hub}}
      {{- end }}
      {{hub- range $repo := $data | base64dec | fromYaml hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: {{hub $repo.name hub}}
        namespace: {{hub index $secret.metadata.annotations "rhacm-policies/target-namespace" hub}}
        labels:
          {{hub range $key, $value := $secret.metadata.labels hub}}
            {{hub- if ne (printf "%.15s" $key) "rhacm-policies/" hub}}
          {{hub $key hub}}: {{hub $value hub}}
            {{hub- end hub}}
          {{hub- end hub}}
        annotations:
          {{hub range $key, $value := $secret.metadata.annotations hub}}
            {{hub- if ne (printf "%.15s" $key) "rhacm-policies/" hub}}
          {{hub $key hub}}: {{hub $value hub}}
            {{hub- end hub}}
          {{hub- end hub}}
      stringData:
        {{hub range $key, $value := $repo hub}}
        {{hub $key hub}}: {{hub $value hub}}
        {{hub end hub}}
      {{hub- end hub}}
    {{hub- end hub}}
  {{hub end hub}}
...
