---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../../apps/rhacs-central/overlays/uat
  - ../../../../apps/rhacs-secured-cluster/overlays/uat
  - ../../../../apps/test-app/overlays/uat
...
