{{- if has .Values.deploymentType (list "operator" "all") }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: multicluster-global-hub-operator-group
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - {{ .Values.namespace }}
...
{{- end }}
