{{- if has .Values.deploymentType (list "argocd" "all") }}
  {{- $namespace := .Values.namespace.argocd }}
  {{- range .Values.appProjects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    {{- range .sourceRepos }}
    - {{ . }}
    {{- end }}
  {{- end }}
...
{{- end }}
