{{- if has .Values.deploymentType (list "argocd" "all") }}
  {{- $namespace := .Values.namespace.argocd }}
  {{- if .Values.appProjects }}
    {{- range $v := .Values.appProjects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $v.name }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    {{- range $repo := $v.sourceRepos }}
    - "{{ $repo }}"
    {{- end }}
  {{- end }}
...
  {{- end }}
{{- end }}
