{{- if has .Values.deploymentType (list "argocd" "all") }}
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: {{ .Values.namespace.argocd }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  networkPolicy:
    enabled: true
  # nodePlacement:
  #   nodeSelector:
  #     node-role.kubernetes.io/infra: ""
  #   tolerations:      # make sure this match what is configure in gitops-service.yaml
  #     - effect: NoSchedule
  #       key: node-role.kubernetes.io/infra
  #       value: reserved
  #     - effect: NoExecute
  #       key: node-role.kubernetes.io/infra
  #       value: reserved
  server:
    enabled: true
    autoscale:
      enabled: {{ .Values.server.autoscale.enabled }}
      {{- if .Values.server.autoscale.enabled }}
      hpa:
        minReplicas: {{ .Values.server.autoscale.minReplicas }}
        maxReplicas: {{ .Values.server.autoscale.maxReplicas }}
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: openshift-gitops-server
      {{- end }}
    route:
      enabled: true
    resources:
      limits:
        cpu: "{{ .Values.server.resources.limits.cpu }}"
        memory: {{ .Values.server.resources.limits.memory }}
      requests:
        cpu: "{{ .Values.server.resources.requests.cpu }}"
        memory: {{ .Values.server.resources.requests.memory }}
  grafana:
    enabled: false
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
  initialSSHKnownHosts: {}
  imageUpdater:
    enabled: false
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: "{{ .Values.dex.resources.limits.cpu }}"
          memory: {{ .Values.dex.resources.limits.memory }}
        requests:
          cpu: "{{ .Values.dex.resources.requests.cpu }}"
          memory: {{ .Values.dex.resources.requests.memory }}
    provider: dex
  applicationSet:
    enabled: true
    resources:
      limits:
        cpu: "{{ .Values.applicationSet.resources.limits.cpu }}"
        memory: {{ .Values.applicationSet.resources.limits.memory }}
      requests:
        cpu: "{{ .Values.applicationSet.resources.requests.cpu }}"
        memory: {{ .Values.applicationSet.resources.requests.memory }}
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  {{- if .Values.disableAdmin }}
  disableAdmin: true     # default false, property not shown on manifest
  {{- end }}
  {{- if .Values.localUsers }}
  localUsers:
    {{- range .Values.localUsers }}
    - name: {{ .username }}
      apiKey: {{ .apiKey }}
      login: {{ .login }}
      tokenLifetime: "3h"
      autoRenewToken: false
    {{- end }}
  {{- end }}
  rbac:
    defaultPolicy: "{{ .Values.rbac.defaultPolicy }}"
    policy: |
      {{- .Values.rbac.policy | nindent 6 }}
    scopes: "[groups]"
  repo:
    enabled: true
    replicas: {{ .Values.repo.replicas }}
    env:
      - name: KUSTOMIZE_PLUGIN_HOME
        value: /etc/kustomize/plugin
    resources:
      limits:
        cpu: "{{ .Values.repo.resources.limits.cpu }}"
        memory: {{ .Values.repo.resources.limits.memory }}
      requests:
        cpu: "{{ .Values.repo.resources.requests.cpu }}"
        memory: {{ .Values.repo.resources.requests.memory }}
    initContainers:
      - name: policy-generator-install
        image: {{ .Values.repo.rhacmPolicyGeneratorImage }}
        command:
          - /bin/bash
        args:
          - -c
          - cp /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator /policy-generator/PolicyGenerator
        volumeMounts:
          - mountPath: /policy-generator
            name: policy-generator
    volumeMounts:
      - mountPath: /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
        name: policy-generator
    volumes:
      - emptyDir: {}
        name: policy-generator
  tls:
    {{- if .Values.tls.customCA }}
    ca:
      configMapName: tls-custom-ca
    {{- else }}
    ca: {}
    {{- end }}
  ha:
    enabled: {{ .Values.redis.ha.enabled }}
    resources:
      limits:
        cpu: "{{ .Values.redis.ha.resources.limits.cpu }}"
        memory: {{ .Values.redis.ha.resources.limits.memory }}
      requests:
        cpu: "{{ .Values.redis.ha.resources.requests.cpu }}"
        memory: {{ .Values.redis.ha.resources.requests.memory }}
  redis:
    enabled: true
    autotls: openshift
    resources:
      limits:
        cpu: "{{ .Values.redis.resources.limits.cpu }}"
        memory: {{ .Values.redis.resources.limits.memory }}
      requests:
        cpu: "{{ .Values.redis.resources.requests.cpu }}"
        memory: {{ .Values.redis.resources.requests.memory }}
  controller:
    enabled: true
    {{- if .Values.controller.sharding.enabled }}
    sharding:
      enabled: {{ .Values.controller.sharding.enabled }}
      replicas: {{ .Values.controller.sharding.replicas }}
    env:
      - name: ARGOCD_CONTROLLER_SHARDING_ALGORITHM
        value: {{ .Values.controller.sharding.algorithm }}
    {{- end }}
    resources:
      limits:
        cpu: "{{ .Values.controller.resources.limits.cpu }}"
        memory: {{ .Values.controller.resources.limits.memory }}
      requests:
        cpu: "{{ .Values.controller.resources.requests.cpu }}"
        memory: {{ .Values.controller.resources.requests.memory }}
  kustomizeBuildOptions: "--enable-helm --enable-alpha-plugins"
{{ .Files.Get "files/resource-exclusion.yaml" | indent 2 }}
...
{{- end }}
