---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
     argocd.argoproj.io/managed-by: openshift-gitops
...
