---
apiVersion: v2
appVersion: 1.9       # the version depends on openshift catalog source, need not necessary match what is specified here
name: openshift-compliance
description: OpenShift Compliance
type: application
version: 1.0
...
