---
apiVersion: v2
name: openshift-compliance
description: OpenShift Compliance
type: application
version: 1.0
appVersion: 1.9    # The OpenShift GitOps version depends on catalog source, need not necessary match what is specified here
...
