---
namespace: openshift-compliance
complianceScan:
  enable: false
  profiles:
    - kind: TailoredProfile
      name: ocp4-cis-tailored            # scan cluster
    - kind: Profile
      name: tailored-ocp4-cis-node       # scan nodes
  schedule:
    minHour: 1
    maxHour: 3
  roles:
    - master
    - worker
...
