---
namespace: openshift-compliance
complianceScan:
  enable: false
  profiles:
    - ocp4-cis-tailored       # scan cluster
    - ocp4-cis-node           # scan nodes
  schedule:
    minHour: 1
    maxHour: 3
  roles:
    - master
    - worker
...
