# using this long winded approach as {{hub ... hub}} function does not support variable expansion
---
object-templates-raw: |
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: openshift-logging-token
        namespace: rhacm-policies
      data:
        {{- if eq (fromClusterClaim "env") "dev" }}
        {{hub copySecretData "rhacm-policies" "openshift-logging-token-dev" hub}}
        {{- end }}
        {{- if eq (fromClusterClaim "env") "uat" }}
        {{hub copySecretData "rhacm-policies" "openshift-logging-token-uat" hub}}
        {{- end }}
        {{- if eq (fromClusterClaim "env") "prod" }}
        {{hub copySecretData "rhacm-policies" "openshift-logging-token-prod" hub}}
        {{- end }}
...
