# copy secret from rhacm-policies namespace to openshift-logging namespace
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: application-log-token
  namespace: openshift-logging
data:
  token: '{{hub fromSecret "rhacm-policies" "openshift-logging-token" "application" hub}}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: infrastructure-log-token
  namespace: openshift-logging
data:
  token: '{{hub fromSecret "rhacm-policies" "openshift-logging-token" "infrastructure" hub}}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: audit-log-token
  namespace: openshift-logging
data:
  token: '{{hub fromSecret "rhacm-policies" "openshift-logging-token" "audit" hub}}'
...
