---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-app
  namespace: openshift-gitops
  labels:
    applications: test-app
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
            - key: managed-hub
              operator: DoesNotExist
            - key: test-app
              operator: Exists
  template:
    metadata:
      name: "{{ name }}-test-app"
      labels:
        applications: test-app
    spec:
      project: gitops
      source:
        repoURL: https://github.com/bkkhoo/argocd.git
        targetRevision: main
        path: kustomize-deployments/test-app/overlays/prod
      destination:
        server: "{{ server }}"
        namespace: test-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      info:
        - name: env
          value: prod
        - name: type
          value: applicationSet
        - name: target
          value: clusters with test-app but without managed-hub labels
...
