# ansible-playbook -i localhost, misc/ansible/create-values-files.yaml
#
---
- name: bootstrap
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - clusters.yaml
    # clusters.yaml file example
    # clusters:
    #   global-hub:
    #     console: <console-url>
    #     api: <api-server-url>
    #     username: <username>
    #     password: <password>
    #     labels:
    #       managed-hub: no
    #       env: prod
    #   prod-hub01:
    #     console: <console-url>
    #     api: <api-server-url>
    #     username: <username>
    #     password: <password>
    #     labels:
    #       managed-hub: yes
    #       env: prod
    #   prod-cluster01:
    #     console: <console-url>
    #     api: <api-server-url>
    #     username: <username>
    #     password: <password>
    #     labels:
    #       managed-hub: no
    #       env: prod

  tasks:
    - name: create values file for each cluster
      loop: "{{ clusters | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      vars:
        _cluster_name: "{{ item.key }}"
        _url: "{{ item.value.api }}"
        _username: "{{ item.value.username }}"
        _password: "{{ item.value.password }}"
        _labels: "{{ item.value.labels }}"
      ansible.builtin.include_tasks: tasks/setup-import-cluster-values.yaml

    - name: change to {{ (clusters | dict2items)[0].key }} context
      ansible.builtin.command:
        cmd: oc config use-context {{ (clusters | dict2items)[0].key }}
...
