---
tlsSecurityProfile:
  type: Modern           # Old, Intermediate, Modern, Custom
  custom:
    ciphers:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-CHACHA20-POLY1305
      - ECDHE-RSA-CHACHA20-POLY1305
    minTLSVersion: VersionTLS12
...
