---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:    # deploy these to all managed hub regardless of environment
  - ../../../apps/rhacm-policies/base
  - ../../../apps/cluster-config/base
  - ../../../apps/rhacs-central/dev
...
