---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:    # deploy these to all managed hub regardless of environment
  - ../../../apps/rhacm-policies/overlays/managed-hub
  - ../../../apps/cluster-config/base
  - ../../../apps/mandatory-operators/base
  - ../../../apps/openshift-logging/base
  - ../../../apps/openshift-serverless/base
  - ../../../apps/openshift-service-mesh/base
  - ../../../apps/metallb/base
  - ../../../apps/dummy-log-receiver/base
  - ../../../apps/dummy-helm-chart/base
...
