# do-nothing job; just mounting pvc to change the state to Bound
---
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-backup-sync-hook
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
spec:
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
        - name: etcd-backup
          image: {{ .Values.syncHookImage.name }}:{{ .Values.syncHookImage.tag }}
          command:
            - /bin/sh
            - -c
            - sleep 3 && exit 0
          volumeMounts:
            - name: snapshot-db-backup
              mountPath: /snapshot-db-backup
            - name: static-resources-backup
              mountPath: /static-resources-backup
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: etcd-backup-sync-hook
      terminationGracePeriodSeconds: 30
      volumes:
        - name: snapshot-db-backup
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.snapshot.name }}
        - name: static-resources-backup
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.staticResources.name }}
...
