---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-backup-sync-hook
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjob
    verbs:
      - get
      - list
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-backup-sync-hook
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-backup-sync-hook
subjects:
  - kind: ServiceAccount
    name: etcd-backup-sync-hook
    namespace: {{ .Values.namespace }}
...
