---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: openshift-gitops
  labels:
    applications: cluster-config
spec:
  goTemplate: true                     # enable go templating for spec.template field
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters:                        # on global-hub, deploy to all clusters except those with managed-hub label
        selector:                      # on managed-hubs, no cluster should have the managed-hub label
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
            - key: managed-hub
              operator: DoesNotExist
    # argocd automatically registers the local cluster (in-cluster) as https://kubernetes.default.svc but does not create a Secret for
    # it by default, meaning it lacks the "argocd.argoproj.io/secret-type: cluster" label; consequently, selectors like matchExpressions
    # and matchLabels will exclude the local cluster. the list generator below include local cluster int the selection.
    - list:
        elements:
          - name: in-cluster
            server: https://kubernetes.default.svc
            metadata:                 # set label so goTemplate does not error
              labels:                 # global-hub does not need project-request-template
                project-template-override: override
  template:
    metadata:
      name: "{{ .name }}-cluster-config"
      labels:
        applications: cluster-config
    spec:
      project: gitops
      sources:
        # configure operator hub
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/operator-hub/base
        # # configure oauth access token timeouts
        # - repoURL: https://github.com/bkkhoo/argocd.git
        #   targetRevision: main
        #   path: helm-charts/oauth
        #   helm:
        #     valuesObject:
        #       env: '{{ index .metadata.labels "env" }}'
        # disable self provisioner
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/self-provisioner/base
        # disable openshift insights and telemetry services
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/openshift-insights/base
        # configure managementState to Removed for openshift samples operator
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/openshift-samples/base
        # configure motd
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/motd/base
        # enable etcd encryption
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/etcd-encryption/base
        # setup etcd backup cronjob
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: helm-charts/etcd-backup
        # configure project request template
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: helm-charts/project-request-template
          helm:
            valuesObject:
              projectTemplateOverride: '{{ if index .metadata.labels "project-template-override" }}true{{ else }}false{{ end }}'
      destination:
        server: "{{ .server }}"
      ignoreDifferences:
        - group: batch                   # the etcd-backup cronjob schedule has random values
          kind: CronJob
          name: etcd-backup
          namespace: etcd-backup
          jsonPointers:
            - /spec/schedule
      syncPolicy:
        automated:
          prune: false       # the config here modify pre-existing resources that are part of openshift
          selfHeal: true     # do not delete the resources when they are no longer defined in git
        syncOptions:
          - CreateNamespace=true
      info:
        - name: env
          value: any
        - name: type
          value: applicationSet
        - name: target
          value: in-cluster and clusters without managed-hub label
...
