---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: openshift-gitops
  labels:
    applications: cluster-config
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true  # prevent child resources from being deleted, when the parent Application is deleted
  generators:
    - clusters:                        # on global-hub, deploy to all clusters except those with managed-hub label
        selector:                      # on managed-hubs, no cluster should have the managed-hub label
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
            - key: managed-hub
              operator: DoesNotExist
  template:
    metadata:
      name: "{{ name }}-cluster-config"
      labels:
        applications: cluster-config
    spec:
      project: iac-gitops
      sources:
        # configure operator hub
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/operator-hub/base
        # disable self provisioner
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/self-provisioner/base
        # disable openshift insights and telemetry services
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/openshift-insights/base
        # configure managementState to Removed for openshift samples operator
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/openshift-samples/base
        # configure motd
        - repoURL: https://github.com/bkkhoo/argocd.git
          targetRevision: main
          path: kustomize-deployments/motd/base
        # # configure project request template
        # - repoURL: https://github.com/bkkhoo/argocd.git
        #   targetRevision: main
        #   path: helm-charts/project-request-template
        #   helm:
        #     parameters:
        #       - name: enableDefaultDenyIngressNetworkPolicy
        #         value: false
      destination:
        server: "{{ server }}"
      syncPolicy:
        automated:
          prune: false       # the config here modify pre-existing resources that are part of openshift
          selfHeal: true     # do not delete the resources when they are no longer defined in git
        syncOptions:
          - CreateNamespace=true
...
