---
object-templates-raw: |
  {{- $obc_secret := lookup "v1" "Secret" "openshift-logging" "loki-s3-bucket-obc" }}
  {{- if and $obc_secret $obc_secret.data }}
    {{- $obc_configmap := lookup "v1" "ConfigMap" "openshift-logging" "loki-s3-bucket-obc" }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: loki-s3-bucket
        namespace: openshift-logging
      stringData:
        bucketnames: {{ $obc_configmap.data.BUCKET_NAME }}
        endpoint: https://{{ $obc_configmap.data.BUCKET_HOST }}:{{ $obc_configmap.data.BUCKET_PORT }}
        region: "{{ $obc_configmap.data.BUCKET_REGION }}"
        access_key_id: {{ $obc_secret.data.AWS_ACCESS_KEY_ID | base64dec }}
        access_key_secret: {{ $obc_secret.data.AWS_SECRET_ACCESS_KEY | base64dec }}
  {{- end }}
...
