# copy secret from managed-hub rhacm-policies namespace to managed-cluster metallb-system namespace
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bgp-password
  namespace: metallb-system
data:
  password: '{{hub copySecretData "rhacm-policies" "password" hub}}'
---
