# copy secret from managed-hub rhacm-policies namespace to managed-cluster metallb-system namespace
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: metallb-bgp-password
  namespace: metallb-system
data:
  '{{hub copySecretData "rhacm-policies" "metallb-bgp-password" hub}}'
---
