# copy secret from hub rhacm-policies namespace to remote cluster openshift-logging namespace
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openshift-logging-bearer-tokens
  namespace: openshift-logging
data:
  '{{hub copySecretData "rhacm-policies" "openshift-logging-bearer-tokens" hub}}'
...
